WordPress/openverse-catalog

.github/release-drafter.yml, .github/workflows/release-drafter.yml
Addresses WordPress/openverse#20.
This PR adds a workflow and associated configuration for Release Drafter.
=> Add configuration and workflow for Release Drafter

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/code-quality.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/general-feature-request.md, .github/ISSUE_TEMPLATE/image-provider-api-integration-request.md, .github/ISSUE_TEMPLATE/infrastructure-improvement.md, .github/ISSUE_TEMPLATE/new-source-suggestion.md
Addresses WordPress/openverse#33.
Closes #115.
=> Update issue templates

src/cc_catalog_airflow/dags/recreate_audio_popularity_calculation.py, src/cc_catalog_airflow/dags/refresh_all_audio_popularity_data.py, src/cc_catalog_airflow/dags/refresh_audio_view_data.py, src/cc_catalog_airflow/dags/refresh_image_view_data.py, src/cc_catalog_airflow/dags/util/popularity/operators.py, src/cc_catalog_airflow/dags/util/popularity/sql.py, src/cc_catalog_airflow/dags/util/popularity/test_sql.py, src/cc_catalog_airflow/local_postgres/0007_openledger_audio_view.sql, src/cc_catalog_airflow/local_postgres/Dockerfile, src/openledger_sql/popularity/03_create_image_standardized_popularity_func.sql, src/openledger_sql/popularity/04_create_image_view.sql, src/openledger_sql/popularity/05_create_audio_popularity_metrics_table.sql, src/openledger_sql/popularity/06_create_audio_popularity_percentile_func.sql, src/openledger_sql/popularity/07_create_audio_popularity_constants_view.sql, src/openledger_sql/popularity/08_create_audio_standardized_popularity_func.sql
This is a cleaned up version of #112. The base of #112 wasn't main branch, and when merged, it added changes to `add_audio_db`(#111) branch, which was already merged into main before. GitHub usually changes PR base branch after its previous base is merged, however, for some reason, it didn't for #112.
When comparing the #112 branch to main to possibly merge it into main, I saw that files that have already been changed in main showed up as modified, with the same changes. So, I decided to open a clean PR instead.
One of the data points we use to rank the search results is the popularity of an item. We use the provider popularity metrics and normalize them so that the popularity value is between 0 and 1. This way, if provider A's most popular item has 100 views, and provider B's most …
=> Add support for other media types to popularity calculations

README.md
Adds additional former contributors
Fixes WordPress/openverse#53
<details>
```
Version 1.1
Suite D4700
indicated in the file; or
(b) The contribution is based …
```
=> Update acknowledgements section

README.md, justfile
Fixes #178 by @sarayourfriend
Adds a new `recreate` recipe that tears everything down and forces a rebuild of the containers.
Just expands on existing recipes but composes them. Hooray! I added the ability to pass parameters to `up` to make it cleaner.
Checkout the branch and run `just recreate` and verify that it truly recreates and rebuilds everything from scratch.
<details>
```
Version 1.1
Suite D4700
license document, …
```
=> Add recreate recipe

.github/ISSUE_TEMPLATE/new-source-suggestion.md
Fixes #177 by @zackkrida
Replaced "CC Search" with "Openverse" in the "New Source Suggestion for CC Search" issue template.
Replaced "CC Search" with "Openverse" in the "New Source Suggestion for CC Search" issue template.
<details>
```
Version 1.1
Suite D4700
(a) The contribution …
```
=> Renamed the source suggestion issue template

README.md
Fixes #186 by @zackkrida 
Adds StockSnap to the monthly DAG list + cleans up the DAG lists by normalizing their structure and alphabetizing the items.
<details>
```
Version 1.1
Suite D4700
have the right to submit it …
```
=> Streamline dag lists in README.md and add StockSnap

justfile
Similar to WordPress/openverse-api#244, this documents the `justfile` and adds `-lu` as the default command.
While setting up my own environment, I also encountered an issue where trying to run `just recreate` as the **first** command errored out. This was because the `dotenv` recipe wasn't a dependency of `recreate`. Although this is a pretty unlikely edge case, I've corrected that behavior in this PR.
1. Delete your `openverse_catalog/.env` file
1. Run `just recreate`
<details>
```
Version 1.1
Suite D4700
San …
```
=> Organize & document `justfile`, fix issue with recreate command

DEPLOY.md, env.template, openverse_catalog/dags/common/dag_factory.py, openverse_catalog/dags/common/slack.py, openverse_catalog/dags/database/loader_workflow.py, openverse_catalog/dags/database/recreate_audio_popularity_calculation.py, openverse_catalog/dags/database/recreate_image_popularity_calculation.py, openverse_catalog/dags/database/refresh_all_audio_popularity_data.py, openverse_catalog/dags/database/refresh_all_image_popularity_data.py, openverse_catalog/dags/database/refresh_audio_view_data.py, openverse_catalog/dags/database/refresh_image_view_data.py, openverse_catalog/dags/maintenance/airflow_log_cleanup_workflow.py, openverse_catalog/dags/oauth2/authorize_dag.py, openverse_catalog/dags/oauth2/token_refresh_dag.py, tests/dags/common/test_slack.py
Fixes #214 by @AetherUnbound
This PR adds an `on_failure_callback` method to the `slack` module which will (in certain conditions) propagate that failure message to Slack. This failure callback has been added to most DAGs.
I also added an `environment` Airflow Variable to the environment-defined variables. This value can be helpful for making decisions about alerting/what actions to take in a given situation depending on whether the instance is being run locally (`dev`) or in production (`prod`).
Lastly I made some minor tweaks to the other `slack` tests to make mock access a bit clearer.
`just test`
If you'd like to test the notification, you'll need to:
1. Set up the Slack hook (defined in the `.env` file)
1. Add an Airflow Variable `force_slack_alert` with value `true`
1. Instigate a …
=> Slack alerting for DAG failures

openverse_catalog/dags/common/etl/scripts/ExtractCCLinks.py, openverse_catalog/dags/common/log_cleanup.py, openverse_catalog/dags/commoncrawl/commoncrawl_etl.py, openverse_catalog/dags/commoncrawl/commoncrawl_scripts/commoncrawl_s3_syncer/SyncImageProviders.py, openverse_catalog/dags/database/image_expiration_workflow.py, openverse_catalog/dags/database/recreate_audio_popularity_calculation.py, openverse_catalog/dags/database/recreate_image_popularity_calculation.py, openverse_catalog/dags/database/refresh_all_audio_popularity_data.py, openverse_catalog/dags/database/refresh_all_image_popularity_data.py, openverse_catalog/dags/database/refresh_audio_view_data.py, openverse_catalog/dags/database/refresh_image_view_data.py, openverse_catalog/dags/maintenance/airflow_log_cleanup_workflow.py, openverse_catalog/dags/providers/brooklyn_museum_workflow.py, openverse_catalog/dags/providers/check_new_smithsonian_unit_codes_workflow.py, openverse_catalog/dags/providers/cleveland_museum_workflow.py, openverse_catalog/dags/providers/europeana_ingestion_workflow.py, openverse_catalog/dags/providers/europeana_workflow.py, openverse_catalog/dags/providers/finnish_museums_workflow.py, openverse_catalog/dags/providers/flickr_ingestion_workflow.py, openverse_catalog/dags/providers/flickr_workflow.py, openverse_catalog/dags/providers/freesound_workflow.py, openverse_catalog/dags/providers/jamendo_workflow.py, openverse_catalog/dags/providers/metropolitan_museum_workflow.py, openverse_catalog/dags/providers/museum_victoria_workflow.py, openverse_catalog/dags/providers/nypl_workflow.py, openverse_catalog/dags/providers/phylopic_workflow.py, openverse_catalog/dags/providers/provider_api_scripts/Thingiverse.py, tests/dags/providers/provider_api_scripts/test_flickr.py
Fixes #199 by @AetherUnbound
As described in #199, these calls are redundant and unnecessary for the DAG/test files. They are useful to keep in files that are likely to be run as individual scripts from the command line, so those ones have been retained.
`just test` and `just run airflow list dags` should both behave normally.
<details>
```
Version 1.1
Suite D4700 …
```
=> Remove unnecessary logging.basicConfig calls

openverse_catalog/dags/common/loader/provider_details.py, openverse_catalog/dags/providers/provider_api_scripts/flickr.py, openverse_catalog/dags/providers/provider_api_scripts/stocksnap.py, tests/dags/providers/provider_api_scripts/resources/flickr/image_data_complete_example.json, tests/dags/providers/provider_api_scripts/test_flickr.py, tests/dags/providers/provider_api_scripts/test_stocksnap.py
Related #292 by @dhruvkb
This PR copy the default categories for images from the API to be used by the Provider API scripts. It uses these categories to complete the Flickr and StockSnap scripts and then fills the `filesize`, `filetype` and `category` columns.
I'm not sure where the rest of the sources come from (from which provider) so it seems to me that the use of the rest of the categories should be incremental as we test each script and fill these columns also. Flickr and StockSnap are selected in order to have more complete sample data for the API.
1. Run the project and from the Airflow UI run these three dags: `flick_workflow`, `stocksnap_workflow` and `tsv_to_postgres_loader`.
2. Wait for some data to be collected.
3. Check for the fields filled in the database. …
=> Add Image Categories

docker/local_postgres/0003_openledger_image_schema.sql, docker/local_postgres/0006_openledger_audio_schema.sql
Fixes #305 by @AetherUnbound
This is a deceptively small PR - it actually accompanies a significant change to the catalog database. On the last few data refreshes we found that there's a capacity for duplicates to exist in the catalog that become impossible to import into the API due to unique indices. This PR carries _only_ the unique indices over (some discussion exists in WordPress/openverse#120 about why we don't want all indices).
:warning: This will definitely take some time to run against production! (And this message also serves as a reminder that we need to apply this in prod too) :warning:
1. `just test`
<details>
<summary>Developer Certificate of …
=> Add unique indices to catalog

openverse_catalog/dags/database/loader_workflow.py
Related to #285, this PR disables scheduling on the TSV loader for the time being. Currently this DAG is run every minute, which is way _way_ more frequent than we need it to be. As we start to get things back up to speed, these extra runs will just clutter the run history and make it difficult for us to track down the runs that actually matter.
Enable the DAG and see that it doesn't automatically trigger every minute.
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and …
```
=> Disable TSV loader scheduling

env.template, openverse_catalog/dags/common/etl/scripts/ExtractCCLinks.py, openverse_catalog/dags/commoncrawl/commoncrawl_etl.py, openverse_catalog/dags/commoncrawl/commoncrawl_scripts/commoncrawl_s3_syncer/SyncImageProviders.py
Fixes #316 by @AetherUnbound
This PR changes the commoncrawl bucket to be configurable via environment variable. I've also reserved a different bucket for us to use when we end up wanting to run this again.
I do not know how to run this so I'm just basing this off of `just lint` and `just test`.
<details>
```
Version 1.1
Suite D4700
By …
```
=> Make commoncrawl bucket configurable, change default

openverse_catalog/dags/common/requester.py
This PR changes a logging line in the `DelayedRequseter` from `info` to `debug`. We don't really need information on a successful request (we're more concerned with failure modes) and this ends up logging every single requests made by the requester. For providers where each image requires a request, this can make the logs huge (e.g.: https://airflow.openverse.engineering/log?dag_id=stocksnap_workflow&task_id=pull_image_data&execution_date=2021-11-01T00%3A00%3A00%2B00%3A00).
Run the Stocksnap DAG and ensure that it doesn't log in a similar manner to the above linked log.
<details>
```
Version 1.1 …
```
=> Change request info log to debug to prevent spam

openverse_catalog/dags/common/dag_factory.py
The current default is 30 minutes. I imagine most providers take longer than this, so for now I'm proposing we bump this up until 12. Once I get a better handle on how long the DAGs take, we can pull this back down.
<details>
```
Version 1.1
Suite D4700 …
```
=> Set default timeout to 12 hours

openverse_catalog/dags/common/slack.py
This fixes a small issue where `textwrap.dedent` was unable to properly remove common indentation because other lines were being added without indentation. This PR removes the attempted indentation allowance altogether so that everything remains aligned.
Cause and exception with slack alerts enabled.
<details>
```
Version 1.1
Suite D4700 …
```
=> Fix inconsistent alignment in slack message text

tests/dags/common/conftest.py
Fixes #343 by @AetherUnbound
In #337 I modified how buckets were being created for testing. In doing so, I neglected to add code that cleaned up the buckets after testing was complete. This PR ensures that the pseudo-random buckets made during testing are destroyed afterwards.
1. Check minio console at localhost:5011 and observe 0 buckets
1. `just test`
1. Check minio console at localhost:5011 and observe 0 buckets
<details>
```
Version 1.1
Suite D4700
Everyone is …
```
=> Remove buckets after testing

openverse_catalog/dags/providers/provider_api_scripts/wikimedia_commons.py
Fixes #140 by @dhruvkb 
Replaces user agent string with correct information pertaining to Openverse.
<details>
```
Version 1.1
Suite D4700
indicated in the …
```
=> Updated user agent for Wikimedia Commons #140

env.template, openverse_catalog/dags/providers/provider_api_scripts/Thingiverse.py, openverse_catalog/dags/providers/provider_api_scripts/brooklyn_museum.py, openverse_catalog/dags/providers/provider_api_scripts/europeana.py, openverse_catalog/dags/providers/provider_api_scripts/flickr.py, openverse_catalog/dags/providers/provider_api_scripts/freesound.py, openverse_catalog/dags/providers/provider_api_scripts/jamendo.py, openverse_catalog/dags/providers/provider_api_scripts/nypl.py, openverse_catalog/dags/providers/provider_api_scripts/smithsonian.py, openverse_catalog/dags/providers/provider_api_scripts/walters_art_museum.py
Fixes #209 by @AetherUnbound
This PR changes the provider API scripts to use [Airflow Variables](https://airflow.apache.org/docs/apache-airflow/stable/concepts/variables.html) rather than environment variables. The rationale/motivation for this can be found in-depth in #209, but the TL;DR is that this will make it easier for us to update the values in production without re-deploying the catalog.
As part of this effort, I've also unified the format for the keys. They now all begin with `AIRFLOW_VAR_` (in accordance with [Airflow's spec](https://airflow.apache.org/docs/apache-airflow/stable/howto/variable.html#storing-variables-in-environment-variables)) _as well as_ `API_KEY_<name>`. This consistency will make it easier to pick out the variables in the UI and within the environment since …
=> Use Airflow Variables for storing API keys

openverse_catalog/dags/common/loader/provider_details.py
Fixes #406
Adds the `OFEO-SG` subprovider to the configuration for the Smithsonian workflow. This is necessary to get the DAG up and running, since it errors on unrecognized providers.
First, try running the `smithsonian_workflow` locally and verify that its pull_data task fails with:
```
File "/usr/local/airflow/openverse_catalog/dags/providers/provider_api_scripts/smithsonian.py", line 365, in _extract_source
raise Exception(f"An unknown unit code value {unit_code} encountered ")
Exception: An unknown unit code value OFEO-SG encountered 
```
Then pull this branch and re-run the DAG. Note this would take a long time to run to completion. What I did was start the DAG, let the `pull_data` task run for about ~1 minute and then manually mark the task as completed. I then grabbed the TSV from …
=> Add OFEO-SG subprovider

openverse_catalog/dags/common/loader/provider_details.py, openverse_catalog/dags/providers/provider_api_scripts/museum_victoria.py, openverse_catalog/dags/providers/provider_api_scripts/wikimedia_commons.py, tests/dags/providers/provider_api_scripts/test_museum_victoria.py
Fixes #390 by @stacimc
The Museum Victoria provider DAG was failing to pull in image data with the following:
```
[2022-02-25, 18:38:14 UTC] {requester.py:49} WARNING - Unable to request URL: https://collections.museumsvictoria.com.au/api/search?has_image=yes&perpage=100&imagelicence=cc+by-nc-nd&page=0.  Status code: 403
[2022-02-25, 18:38:19 UTC] {requester.py:49} WARNING - Unable to request URL: https://collections.museumsvictoria.com.au/api/search?has_image=yes&perpage=100&imagelicence=cc+by-nc-nd&page=0.  Status code: 403
[2022-02-25, 18:38:24 UTC] {requester.py:49} WARNING - Unable to request URL: https://collections.museumsvictoria.com.au/api/search?has_image=yes&perpage=100&imagelicence=cc+by-nc-nd&page=0.  Status code: 403
```
I took a look at the [API …
=> Update API requests for Museum Victoria DAG

openverse_catalog/dags/providers/cleveland_museum_workflow.py, openverse_catalog/dags/providers/wikimedia_workflow.py
Fixes #379 by @AetherUnbound
This PR corrects the schedule intervals for the Cleveland Museum and Wikimedia Commons provider ingestion DAGs. It looks like the intervals were accidentally swapped from `@monthly` -> `@daily` and `@daily` -> `@monthly` respectively as part of #163. These two DAGs appear to be the only ones affected.
1. Run `just db-shell airflow`
1. Run `select dag_id, schedule_interval from dag order by 1;`
1. Check that Wikimedia Commons is `@daily` and Cleveland Museum is `@monthly`
<details>
```
Version 1.1
1 …
```
=> Fix schedule intervals on Cleveland Museum & Wikimedia Commons

.pre-commit-config.yaml, openverse_catalog/dags/retired/common/pg_cleaner.py, requirements.txt, tests/dags/common/storage/test_columns.py
This PR resolves a CI failure we're observing on `main` due to some dependency incompatibilities with black: https://github.com/psf/black/issues/2964
As a result, some new `black` checks were also applied to several files :slightly_smiling_face:
Watch CI run successfully! You can also check this branch out and run `just lint`.
<details>
```
Version 1.1
Suite D4700 …
```
=> Upgrade black to 22.3.0

openverse_catalog/dags/providers/provider_api_scripts/flickr.py, tests/dags/providers/provider_api_scripts/test_flickr.py
Fixes #407 by @zackkrida 
Adds the [`safe_search` query_param](https://www.flickr.com/services/api/flickr.photos.search.html), set to 'safe', to our search query in the Flickr provider script. This _should_ filter out results that are Moderate or Restricted as defined by Flickr's [content safety levels](https://www.flickrhelp.com/hc/en-us/articles/4404064374164-Set-the-Safety-Levels-of-Your-Flickr-Content-or-Account).
You should at least run the Flickr provider DAG and verify that you start seeing results written to disk. I'm less certain how to test the actual filtering.
<details>
```
Version 1.1 …
```
=> Use safe_search param to restrict results from Flickr

openverse_catalog/dags/common/loader/loader.py, openverse_catalog/dags/common/loader/reporting.py, openverse_catalog/dags/common/loader/sql.py, openverse_catalog/dags/common/provider_dag_factory.py, tests/dags/common/loader/test_loader.py, tests/dags/common/loader/test_reporting.py, tests/dags/common/loader/test_sql.py
Fixes #469 by @AetherUnbound
This PR also builds off #442 
This PR separates the various metrics that we can collect at each step along the loading pipeline and attempts to report the values at each stage. This will help give us a clearer picture of which steps are affecting the final upserted count the most.
I've also added a fix for cases where AWS returns a string for certain values that we had expected to be integers.
Since we're recording more metrics and the dictionary/XComs were becoming unwieldy, I opted to put them all into a `NamedTuple` and pass that along instead. Since we're pickling the XComs, we don't have to worry about serializing that value ourselves. Airflow also displays the Python `repr` value in the XComs UI!
1. `just test`
1. Run the `staten_museum_workflow` DAG …
=> Improved load reporting

docker/airflow/Dockerfile, docker/airflow/wait_for_db.py, env.template, openverse_catalog/dags/common/provider_dag_factory.py, requirements_prod.txt, tests/dags/common/sensors/test_single_run_external_dags_sensor.py
Fixes #498 by @AetherUnbound
This PR upgrades Airflow to 2.3.0, and python to 3.10. I've also addressed some deprecation warnings that came up during testing.
One particularly exciting feature is the new "grid" view, which will replace the "tree" view. It's a lot more understandable!
1. `just test`
1. Run some DAGs!
<details>
```
Version 1.1
Suite D4700 …
```
=> Upgrade Airflow to 2.3, python to 3.10

openverse_catalog/dags/commoncrawl/commoncrawl_etl.py, openverse_catalog/dags/commoncrawl/sync_commoncrawl_workflow.py, openverse_catalog/dags/database/image_expiration_workflow.py, openverse_catalog/dags/database/loader_workflow.py, openverse_catalog/dags/maintenance/airflow_log_cleanup_workflow.py, openverse_catalog/dags/oauth2/authorize_dag.py, openverse_catalog/dags/oauth2/token_refresh_dag.py
Fixes #241 by @AetherUnbound 
Some of our DAG definitions are defined in an unnecessarily verbose way. This PR cleans up these cases, as well as cleaning up some unused imports and making use of the `DAG_DEFAULT_ARGS` constant where applicable.
* Where I've started using `DAG_DEFAULT_ARGS`, if the DAG previously didn't define an `execution_timeout` I explicitly set it to `None` here rather than allowing the default 1 hour. These DAGs do not have available historical data that would let me set sensible timeouts. This will need to be monitored when they are turned on.
`just up` and verify that all of the affected DAGs still load in Airflow.
You can also inspect the `Details` page for each DAG in the UI to verify the correct parameters are applied. Unfortunately to my knowledge there doesn't …
=> Create DAG objects at top level

openverse_catalog/dags/maintenance/pr_review_reminders/pr_review_reminders_dag.py, tests/dags/test_dag_parsing.py
Quick follow up to #553 to update the module import location within the DAG. I've also added the DAG to the list of DAGs to check in `test_dag_parsing.py` (which I had forgotten about). We might want to see about running a similar command to `just run airflow dags list-import-errors` or have Airflow fill up the DagBag itself so we don't have to explicitly add DAGs to this test when we create new ones. I can't remember why we took the individual approach, perhaps to show individual errors rather than aggregate them all?
On main, `just run airflow dags list-import-errors` should return this message:
```
############################################################################################################################################################################################### …
```
=> Fix module import for PR review reminder DAG

openverse_catalog/dags/common/github.py
Fixes #552 by @zackkrida
`request`'s `data` parameter sends multipart form data. You need to pass `json` to pass a JSON body (TIL!). This fixes the issue.
I posted [this comment](https://github.com/WordPress/openverse-catalog/issues/552#issuecomment-1166701034) using the updated code in this PR by using `just ipython`, importing `GitHubAPI`, instantiating it with a PAT and calling `post_issue_comment`.
You could try what I mention above to check that the request works now.
- [N/A] I added or updated tests for the changes I made (if applicable).
- [N/A] I added or updated documentation (if applicable).
<details>
```
Developer …
```
=> Post comments using JSON instead of form data

README.md
Fixes #[277](https://github.com/WordPress/openverse/issues/277) by @[krystal](https://github.com/krysal)
Header with a banner image and some useful links (to the project board, the Make blog, Slack, etc.) added.
<details>
```
Version 1.1
Suite D4700 …
```
=> Unify header added

openverse_catalog/dags/common/loader/provider_details.py
Fixes #611 by @obulat 
Updated Openverse URL in the user agent string
<details>
```
Version 1.1
Suite D4700
indicated in the file; or
(b) The contribution is …
```
=> Update Openverse URL in the user agent string

openverse_catalog/dags/common/loader/reporting.py, openverse_catalog/dags/providers/provider_dag_factory.py, tests/dags/common/loader/test_reporting.py
Fixes #468 by @AetherUnbound
This PR adds an additional section to the reported ingestion metrics slack message which also includes the date range for the data ingested. This date range only shows up for `dated` DAGs, as other DAGs are assumed to ingest the entire dataset on each scheduled run.
Run a DAG and see that the completion message includes dated information!
<details>
```
Version 1.1
Suite D4700
license document, …
```
=> Add date range to ingestion load reports

tests/dags/providers/provider_api_scripts/test_stocksnap.py
Addresses (in part) #624 by @AetherUnbound
This PR alters the Stocksnap tests by mocking the `_get_filesize` function, which was calling out to an external API. The test speed improved dramatically:
```
Results (43.53s):
1296 passed
Results (7.93s):
1296 passed
```
I will investigate in a follow-up PR why pytest-socket continues to not behave as expected.
Try `just test` on both `main` and this branch and observe a similar time differential.
<details>
```
Version 1.1
Suite D4700
Everyone is …
```
=> Patch Stocksnap tests that called out to external API

openverse_catalog/dags/data_refresh/data_refresh_task_factory.py
This PR is a companion to WordPress/openverse-api#707.
This PR splits the data refresh workflow into two steps.
- `INGEST_UPSTREAM`
- `POINT_ALIAS`
<details>
```
Version 1.1
Suite D4700
have the right to submit it …
```
=> Update data refresh DAG to account for manual go-live

openverse_catalog/dags/providers/provider_dag_factory.py, openverse_catalog/dags/providers/provider_ingestion_workflow_dag_factory.py, openverse_catalog/dags/providers/provider_ingestion_workflows.py, openverse_catalog/dags/providers/provider_workflow_dag_factory.py, openverse_catalog/dags/providers/provider_workflows.py
* Adds a `load_timeout` option to the `ProviderWorkflow` configurations to control the `execution_timeout` of the load data step. Defaults to 1hr (which is the current default, so DAGs are by default unchanged)
* Removes `retries` for the load data step, as errors in this step are non-transient and don't benefit from being retried
* Updates the timeouts for the Finnish Museum dag, which is currently timing out on both the pull and load steps.
`just up`, make sure the DAGs all load. You can inspect the Task Instance Details for the pull and load steps of a few DAGs to make sure the timeouts look correct. To do this you will have to have a DagRun, so you may need to trigger the Dag. The Task Details view is accessible from the menu by clicking on the task in the Graph view. …
=> Adjust load data timeout and retries

openverse_catalog/dags/common/requester.py
Fixes #624 by @AetherUnbound
This PR _does_ address the root cause of #624, wherein `pytest-socket` exceptions were being raised and squelched by the `DelayedRequester` class unconditionally. This meant that, even though requests would not get through, the entire request retry mechanism would run and take up a significant amount of time.
Since the specific exception we need to catch will only be available in the dev container and not the one we use in production, we also needed to set up an import catch for that particular case. This change ensures that if that specific exception is met (or any others we might need to single out in the future), it is re-raised for the testing infrastructure to report rather than being caught.
~~**Note**: CI will fail for this DAG until we merge #628 and …
=> Re-raise pytest-socket errors within DelayedRequester

openverse_catalog/dags/common/constants.py, openverse_catalog/dags/common/operators/postgres_result.py, openverse_catalog/dags/data_refresh/dag_factory.py, openverse_catalog/dags/data_refresh/record_reporting.py, openverse_catalog/dags/database/report_pending_reported_media.py, tests/dags/common/operators/test_postgres_result.py, tests/dags/data_refresh/test_record_reporting.py
Fixes #466 by @AetherUnbound
This PR adds a few new steps to the data refresh DAGs which gather the record counts for a provided media table from the API before and after the data refresh, and then report the difference to Slack. 
The easiest way of adding this to the DAG was to include a few `PostgresOperator` steps which would query the record count before and after the refresh. Unfortunately, the `PostgresOperator` doesn't push the return value to XComs by default. In order to facilitate that behavior here (and in future DAGs), I added a `PostgresResultOperator`. This operator is identical to the `PostgresOperator`, save that it allows a `handler` to be passed in, which in-turn is passed down to the `PostgresHook` when `PostgresHook::run` is called. It also returns the results of the …
=> Data refresh record difference reporting

justfile, openverse_catalog/dags/common/github.py, openverse_catalog/dags/maintenance/pr_review_reminders/pr_review_reminders.py, tests/dags/maintenance/test_pr_review_reminders.py, tests/factories/github/__init__.py, tests/factories/github/branch_protection.json, tests/factories/github/comment.json, tests/factories/github/pull.json, tests/factories/github/review.json
Fixes #571  by @sarayourfriend 
1. Fixes the formatting of the markdown of the comment and adds some additional explanation footnotes to the comment
2. Deletes previous review comments when leaving a re-ping to declutter the PR conversation history
3. Re-pings when the PR has been updated since the last reminder and the PR is due again
4. Does not ping if the PR already has two approvals
Checkout this PR locally, add a GitHub PAT with access to the relevant repositories in your local Airflow variables under the name `GITHUB_API_KEY`. Run the dag in your local airflow and check that the dry run logs work. Note that right now I only see one reminder being generated, this is pretty much up to the state of our repositories so the unit tests should be the primary indication of whether this DAG …
=> Re-ping if PR is updated and don't ping if 2 approvals exist

README.md
Fixes #661 by @ramadanomar
The handbook hyperlink under the banner leads you to a page that doesn't exist. I already created an issue on the openverse-catalog repo but it applies to all openverse repos. 
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in …
```
=> Updates Handbook Link

openverse_catalog/dags/common/constants.py
This PR adds the `CONTACT_EMAIL` (presently openverse@wordpress.org) to the `email` section of the DAG default args. This is a precursor to getting alert emails working, since Airflow first needs an address to send said emails to.
You should be able to go to the "Details" page of any DAG locally and see that `email` is now defined under the "Default Args" section.
<details>
```
Version 1.1
Suite D4700
license document, but …
```
=> Add Openverse email to DAG default args

openverse_catalog/dags/providers/provider_workflows.py
Follow up to #549 and the launch of the iNaturalist DAG
We observed that iNaturalist was going to take longer than 24 hours to pull and 1 hour to load, so we increased both timeouts to 5 days.
**Note**: This change was made in-place in production and reflects the current diff. We may alter these timeouts based on what we feel is realistic and how much data we'd like to try and process.
<details>
```
Version 1.1
Suite D4700 …
```
=> Bump iNaturalist timeouts to 5 days

openverse_catalog/dags/providers/provider_api_scripts/inaturalist.py
The `args` to `__init__` were not being passed through to the call to `super()` in iNaturalist. This means that if you supply dagrun configuration options like the new `initial_query_params` or `skip_ingestion_errors`, they will not be properly set on the class.
PR just updates `__init__` to pass all args through.
Manually trigger iNaturalist with dagrun conf, for example I used `{"initial_query_params": {"offset_num": 10000}}`
Inspect the logs to verify the conf was used. In my case I looked at the logs for `pull_data` and saw `Using initial_query_params from dag_run conf: {"offset_num": 10000}`.
<details>
```
Developer …
```
=> Initialize iNaturalist with dagrun conf

openverse_catalog/dags/providers/provider_api_scripts/inaturalist.py, openverse_catalog/dags/providers/provider_api_scripts/metropolitan_museum.py, openverse_catalog/dags/providers/provider_api_scripts/museum_victoria.py, openverse_catalog/dags/providers/provider_api_scripts/science_museum.py, openverse_catalog/dags/providers/provider_api_scripts/stocksnap.py
In #707 we noticed that iNaturalist was overriding `__init__` but not passing through `*args` to `super`. This prevents configuration options set up in the dagrun conf from being initialized correctly on the ingester class.
After reviewing the other provider scripts that had already been refactored before the addition of that conf arg, I noticed that we needed to update several others!
For each of Museum Victoria, Science Museum, and Stocksnap:
* try manually running the DAG with a dagrun conf setting `initial_query_params`
* verify in the logs of the `pull_data` task that the DAG used your supplied params
<details>
```
Developer …
```
=> Fix dagrun conf for provider scripts

docker/airflow/Dockerfile, openverse_catalog/dags/commoncrawl/commoncrawl_etl.py, requirements_prod.txt, tests/dags/common/sensors/test_single_run_external_dags_sensor.py
This PR bumps Airflow from 2.3.3 to 2.3.4.
This mitigates some known security issues. Dues to an updated constraints file, I also needed to make some changes to the commoncrawl DAG since `S3PrefixSensor` no longer exists.
I tested this locally and things were looking good!
Build and run locally.
<details>
```
Version 1.1
Suite D4700
By …
```
=> Bump Airflow version to 2.3.4

openverse_catalog/dags/providers/provider_dag_factory.py, openverse_catalog/dags/providers/provider_workflows.py
This PR adds a `legacy-ingestion` tag to any provider ingestion DAG which has not yet been refactored. This was instigated by some testing I was performing locally - I wasn't sure which DAGs I could run which would actually respect `ingestion_limit` (or any other feature we're building using the new `ProviderDataIngester` class!). This makes it very easy to determine which DAGs are legacy and which use the new class.
1. Visit http://localhost:9090/ and observe the new tags
1. Visit http://localhost:9090/home?tags=legacy-ingestion to see _only_ the legacy provider DAGs
1. (Optional) Add a `tags=` override to any of the [provider workflows](https://github.com/WordPress/openverse-catalog/blob/8e2b676c0dd5d8e06b3272a74784a1b3db4c5acb/openverse_catalog/dags/providers/provider …
=> Add tags option for provider workflows & "legacy-ingestion" tag

openverse_catalog/dags/providers/provider_api_scripts/smk.py, tests/dags/providers/provider_api_scripts/test_smk.py
Fixes #793 by @zackkrida 
Updates the SMK provider script to use English instead of Danish. This doesn't update _all_ text, or titles of works, as some do not have English available. For an example of what data this actually changes you can compare these URLs in your browser or with `curl`:
- https://api.smk.dk/api/v1/art/search/?keys=*
- https://api.smk.dk/api/v1/art/search/?keys=*&lang=en
2. Run the SMK dag locally through the Airflow UI
3. Check for _some_ English titles in the results
4. Make sure tests pass
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The Linux …
```
=> Use English for SMK results

openverse_catalog/dags/providers/provider_api_scripts/nypl.py, openverse_catalog/dags/providers/provider_api_scripts/provider_data_ingester.py, openverse_catalog/dags/providers/provider_workflows.py, tests/dags/providers/provider_api_scripts/resources/nypl/metadata.json, tests/dags/providers/provider_api_scripts/test_nypl.py
Fixes #590 by @stacimc, fixes #710 by @AetherUnbound 
This PR replaces #546. Changes in the NYPL script:
- use of the DataIngester class. NYPL requests a single image API endpoint to get each image's data. To enable delayed requests for _detail_ endpoints, I added `get_detail_json` method to the base class, but I think its API can be greatly improved.
- filetype detection.
- category is set as `photograph`  for items with `photograph` as their `genre`.
- creator is added when there is a single creator, not only when there's an array of creators.
- `date_created` added to `meta_data`.
- `topics` extracted and added to `meta_data`. I was wondering if we should combine `physicalDescription` and `topics` into a single string and save it as `description` to improve the search relevancy for …
=> Refactor NYPL script to use ProviderDataIngester class

.github/ISSUE_TEMPLATE/image_provider_api_integration_request.yml, .pre-commit-config.yaml, docker-compose.override.yml, docker-compose.yml
Addresses WordPress/openverse#316 by @dhruvkb
This PR uses the new pre-commit config introduced in WordPress/openverse#330 and fixes the code so that the lint checks pass.
<details>
```
Version 1.1
Suite D4700
have …
```
=> Unify pre-commit config across repos

openverse_catalog/dags/providers/provider_dag_factory.py
Fixes #907 by @AetherUnbound
This PR adds an additional DAG tag for provider ingestion DAGs to show distinction between dated & full ingestion.
1. `just up`
1. Check that the provider DAGs either show `ingestion: dated` or `ingestion: full`
<details>
```
Version 1.1
Suite D4700 …
```
=> Add DAG tag for showing dated vs full ingestion

openverse_catalog/dags/providers/provider_reingestion_workflows.py
Fixes #955 by @AetherUnbound
Hours property changed to 16 for the Met museum ingestion flow
```diff
- pull_timeout=timedelta(hours=12),
+ pull_timeout=timedelta(hours=16),
```
N/A
errors.
<details>
```
Version 1.1
Suite D4700
(a) The …
```
=> Met Museum Reingestion timeout set to 16 hours

DEPLOYMENT.md
As the title says, this PR updates the deployment docs to suggest using the `just bump` command for bumping versions. Identified by @stacimc.
errors.
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole or in …
```
=> Update the deployment docs to showcase the bump version command

openverse_catalog/dags/maintenance/rotate_db_snapshots.py
I incorrectly applied the code from Madison's suggestion and it is causing a JSON parse error (because the ARN shouldn't be parsed as JSON at all :sweat_smile:)
https://github.com/WordPress/openverse-catalog/pull/904#discussion_r1048979669
Not sure? Can a unit test be written for this kind of thing?
errors.
<details>
```
Version 1.1
Suite D4700
license document, but changing it …
```
=> Fix rotate_db_snapshot ARN template

openverse_catalog/dags/common/storage/audio.py, openverse_catalog/dags/common/storage/media.py, tests/dags/common/storage/test_audio.py, tests/dags/common/storage/test_media.py, tests/dags/providers/provider_api_scripts/test_stocksnap.py
Fixes #877 by @AetherUnbound
This PR adds a new validation function to the `MediaStore` class which is used to ensure that both `filesize` and `duration` do not exceed the Postgres integer maximum value.
I'm hoping I put the validation in a reasonable enough place, but if folks who have worked with the stores before (CC @obulat) have other suggestions I'm open to it!
1. Run the tests locally
1. Optionally, ensure that the reproduction criteria defined in #730 succeeds under this PR
errors.
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The Linux …
```
=> Set `filesize` and `duration` overflowed values to `None`

openverse_catalog/dags/providers/provider_api_scripts/freesound.py, openverse_catalog/dags/providers/provider_workflows.py
Fixes #932 by @stacimc
This PR temporarily increases the API request delay from the default (1 second) to 5 seconds. It also changes the `pull_timeout` from the default (24 hours) to 48 hours.
The pull timeout change should be shown on the task instance detail page for Freesound's `pull_media` task (see `execution_timeout`). Although if you _do_ run it locally you may also run into #659.
errors.
<details>
```
Version 1.1
Suite D4700
Everyone is …
```
=> Temporarily increase Freesound delay & timeout

openverse_catalog/dags/providers/provider_api_scripts/phylopic.py, tests/dags/providers/provider_api_scripts/test_phylopic.py
Fixes #813 by @stacimc
This PR removes the pieces of the Phylopic DAG which allowed differentiation between dated & full runs. Since we no longer wish to make full runs of the DAG, this code is no longer necessary and has been removed.
Run `just recreate` and then turn the Phylopic DAG on. It should skip the first 7 runs then have a few runs after that which process data appropriately.
errors.
<details>
```
Version 1.1
Suite D4700
Everyone is …
```
=> Make Phylopic a dated-only DAG

openverse_catalog/dags/common/slack.py, openverse_catalog/dags/providers/provider_reingestion_workflows.py
Fixes #954 by @AetherUnbound 
Increased pullout_time to 16 hours
errors.
<details>
```
Version 1.1
Suite D4700 …
```
=> Increase Europeana reingestion timeout to 16 hours

requirements_tooling.txt
Fixes #988 by @AetherUnbound 
Removed the additional dependencies that were not required :
isort , black ,flake8 
fromrequirements_tooling.txt
-----------------------------------------
errors.
<details>
```
Version 1.1
Suite D4700
(a) …
```
=> Remove unnecessary dev dependencies

.github/ISSUE_TEMPLATE/airflow_alert.md
This PR adds an "Airflow Alert" issue template, for use by maintainers when converting Airflow alerts in Slack to GitHub issues. This is modeled off the [Sentry bug issue template](https://github.com/WordPress/openverse-catalog/blob/52acf96b98bf81c7ee20358486f38c6254d91e96/.github/ISSUE_TEMPLATE/sentry_bug.md).
I also made a `🌬️ tooling: airflow` label for these issues.
errors.
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy …
```
=> Add an "Airflow Alert" issue template

openverse_catalog/dags/maintenance/pr_review_reminders/pr_review_reminders.py
This PR fixes an issue we're seeing with the PR reminder DAG ([Airflow log link](https://airflow.openverse.engineering/log?execution_date=2023-02-22T00%3A00%3A00%2B00%3A00&task_id=pr_review_reminder_operator&dag_id=pr_review_reminders&map_index=-1), attempts 7-9) wherein the check is running against repos that are now archived. Both the API and the Frontend are now part of the `openverse` main repo, so we can remove those from the list of repos to check.
Run it in prod!
errors.
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The Linux Foundation and …
```
=> Remove API & Frontend repos from PR reminder check

tests/dags/common/loader/test_sql.py, tests/dags/common/test_requester.py
Tiny PR to speed up some tests :slightly_smiling_face:
`just test` and see the difference! You can also run `just test --durations=10` on main and on this branch to see what the top 10 longest tests are.
errors.
<details>
```
Version 1.1
Suite D4700
By making a contribution to this project, I …
```
=> Speed up some tests

openverse_catalog/dags/data_refresh/data_refresh_task_factory.py, openverse_catalog/dags/data_refresh/data_refresh_types.py, openverse_catalog/dags/data_refresh/refresh_view_data_task_factory.py
This PR relates to [the ongoing effort regarding data refreshes after the increase in data from iNaturalist](https://make.wordpress.org/openverse/2023/02/21/post-inaturalist-data-refresh-status/).
It adjusts a number of aspects about the data refresh DAG:
- The image matview refresh has been extended from 24 to 72 hours based on evidence of current timings (see the Make post above)
- Removes retries from the image data refresh step
- Corrects the docstring referencing the data refresh timeout parameter
- Changes the data refresh timeout type from seconds to a timedelta; this makes the value more consistent within the other timeouts on the data refresh workflow definition
Try to run a data refresh locally if you'd like!
errors. …
=> Increase image matview refresh timeout, remove retries, better timeouts

.github/ISSUE_TEMPLATE/code_quality.md, .github/ISSUE_TEMPLATE/infrastructure_improvement.md
Fixes #989 #991
removed extra implementations and extra lines .
=> Remove Implementation section from issue templates

openverse_catalog/dags/providers/provider_api_scripts/flickr.py, tests/dags/providers/provider_api_scripts/test_flickr.py
The Flickr API will return a maximum of 4,000 unique records per query. Accordingly we raise an error when more than 4,000 records are ingested, since this means we likely need to reduce the batch sizes.
Although Flickr is not yet enabled in production, while testing locally I noticed that we're encountering batches >4k occasionally. That's because when we're generating the time slices, we base the size of the slice off of the _result count reported by the Flickr API_, which is known to frequently be exceeded. Eg: the API will say there are 3,801 records in a particularly time range, but when we go to actually ingest them we'll find there are actually 4,005 and the error will be raised.
This PR accommodates this by lowering `max_records` to 3000, so we'll attempt to generate time slices …
=> Adjust Flickr max records to account for incorrect reporting

openverse_catalog/dags/providers/provider_api_scripts/flickr.py, openverse_catalog/dags/providers/provider_api_scripts/provider_data_ingester.py, openverse_catalog/dags/providers/provider_api_scripts/time_delineated_provider_data_ingester.py
* Adds some logs that would be helpful in production
* Tweaks the Flickr time delineation settings, specifically to try to default to larger time slices when possible. I'm doing this based on behavior I've seen in production, namely:
* The record count is not typically exceeding the `max_records` _by much_ -- meaning we're splitting more aggressively than is merited in typical cases
* The Flickr API appears to be more fickle for time slices 5min and under, producing many more duplicates due to 'fuzzing' the range -- meaning that we actually become **more** at risk of exceeding the 4k maximum if we over-optimize with slices that are too small
Try running the Flickr DAG. You can try manually triggering a couple of runs to test it with the dates that have caused errors in production, which …
=> Tweak Flickr time division settings, add logs

DAGs.md, openverse_catalog/dags/database/terminate_long_queries_workflow.py
Creates a DAG which runs every 15 minutes and terminates queries in the API DB matching a particular query string.
I had trouble coming up with meaningful unit tests for this, but was able to test it locally by:
* First I changed the `QUERY_TO_TERMINATE` to `select pg_sleep(60)` locally so that I could use a query that will actually take a long time in the local env.
* Run the catalog and API simultaneously in your local environment.
* From within the `openverse/api` directory in the `openverse` repo, run `just dbshell` to get a db connection
* Run `select pg_sleep(60)` (the query we want to terminate in this test) in the api db
* Trigger the new DAG in your local Airflow
Observe that the query is terminated.
I also tried running a different query (`select pg_sleep(30)`) and verifying …
=> Add DAG for terminating long-running queries

DAGs.md, openverse_catalog/dags/database/terminate_long_queries_workflow.py
This PR lowers the period of DAG from 15 to 7 minutes.
=> Adjust schedule for long running queries termination

openverse_catalog/dags/maintenance/flickr_audit_sub_provider_workflow.py
Fast-follow to #1034 
No behavior should be changed here, just a quick fast-follow to add a `SuggestedSubProvider` type for readability.
Remove [this line](https://github.com/WordPress/openverse-catalog/blob/main/openverse_catalog/dags/common/loader/provider_details.py#L62) from `provider_details.py` (to ensure that the DAG will report something). Then run the `flickr_audit_sub_provider_workflow` and make sure that it runs without error and reports the removed sub-provider as a suggestion.
errors.
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The …
```
=> Add SuggestedSubProvider type

.github/dependabot.yml
Follow up to https://github.com/WordPress/openverse/pull/1026 for the catalog, this PR adds the newly required stack label to the dependabot PRs.
Merge & wait
errors.
<details>
```
Version 1.1
Suite D4700 …
```
=> Add required stack label to dependabot PRs

docker/local_postgres/Dockerfile
Small devex change which was necessary for some testing on #1060 (since v3.2.0 didn't allow the use of `\copy`). This PR bumps the version of pgcli used in the dev postgres container.
1. `just build`
2. `just db-shell` should print out v3.5.0 when it starts up (rather than v3.2.0)
errors.
<details>
```
Version 1.1
Suite D4700 …
```
=> Update pgcli version to 3.5.0

openverse_catalog/dags/providers/provider_api_scripts/flickr.py
Quick PR to improve the logging for the number of requests made by the Flickr DAG.
* logs once at the end of ingestion, ensuring total count is logged and is easier to find
* includes the requests used to generate time slices.
Run the Flickr DAG and verify you see the log.
errors.
<details>
```
Version 1.1
Suite D4700
Developer's …
```
=> Improve request count logging for Flickr

README.md
Fixes #1076  by @AetherUnbound
errors.
<details>
```
Version 1.1
Suite D4700
indicated in the file; or
(b) The …
```
=> Update references to just airflow in README #1076 

openverse_catalog/dags/data_refresh/data_refresh_types.py
While we work on a new approach to the data fresh, this is an experiment to see how long the image matview refresh takes. We are extending the timeout to 21 days.
errors.
<details>
```
Version 1.1
Suite D4700 …
```
=> Extend image matview refresh to 21 days

tests/dags/providers/provider_api_scripts/test_wikimedia_commons.py
It looks like a linting error was somehow missed in the last PR; not sure if the fact that it was on a fork is relevant. This PR just commits the linting updates.
None needed
errors.
<details>
```
Version 1.1
Suite D4700
(a) The …
```
=> Fix linting
