WordPress/openverse-catalog

src/cc_catalog_airflow/dags/provider_api_scripts/brooklyn_museum.py, src/cc_catalog_airflow/dags/provider_api_scripts/cleveland_museum_of_art.py, src/cc_catalog_airflow/dags/provider_api_scripts/finnish_museums.py, src/cc_catalog_airflow/dags/provider_api_scripts/museum_victoria.py, src/cc_catalog_airflow/dags/provider_api_scripts/raw_pixel.py, src/cc_catalog_airflow/dags/provider_api_scripts/test_raw_pixel.py, src/cc_catalog_airflow/dags/provider_api_scripts/walters_art_museum.py
Addition of the testing and linting workflows surfaced a couple of errors that were added in the last commit:
- The `test_raw_pixel.py` had some changes from a different PR, which do not pass. The changes were reverted, and will be added in a different PR.
- There was a duplicate import in `raw_pixel.py` script. I removed that, and added a blank line between the standard library and local package imports for readability.
=> Fix failing test, improve import readability

src/cc_catalog_airflow/local_s3/Dockerfile, src/cc_catalog_airflow/requirements_dev.txt, src/cc_catalog_airflow/requirements_prod.txt
The update of urllib3 in #86 has caused a dependency version mismatch. This is causing the CI build failures at now.
This PR updates the versions of boto3, botocore and ipython to fix the build.
The local_s3 Docker image was also updated from Python3.7 to the Python:3.9 version, too.
=> Fix the dependency version conflict

.github/workflows/lint.yml, .github/workflows/push_pull_request_test.yml
Fixes #96
This PR restricts GitHub actions to run on push only to the main branch to make sure that the linting and testing CI actions are not run twice.
I had used 'master' branch by mistake, and had to rename the branch because of that. Renaming a PR branch closes that PR, apparently.
Signed-off-by: Olga Bulat obulat@gmail.com
=> Run ci on main push only

.github/workflows/release-drafter.yml
We change the default branch name from develop/master to main, this PR updates the action accordingly.
=> Run release drafter action on push to main branch

src/cc_catalog_airflow/dags/provider_api_scripts/brooklyn_museum.py, src/cc_catalog_airflow/dags/provider_api_scripts/cleveland_museum_of_art.py, src/cc_catalog_airflow/dags/provider_api_scripts/europeana.py, src/cc_catalog_airflow/dags/provider_api_scripts/finnish_museums.py, src/cc_catalog_airflow/dags/provider_api_scripts/flickr.py, src/cc_catalog_airflow/dags/provider_api_scripts/metropolitan_museum_of_art.py, src/cc_catalog_airflow/dags/provider_api_scripts/museum_victoria.py, src/cc_catalog_airflow/dags/provider_api_scripts/nypl.py, src/cc_catalog_airflow/dags/provider_api_scripts/phylopic.py, src/cc_catalog_airflow/dags/provider_api_scripts/raw_pixel.py, src/cc_catalog_airflow/dags/provider_api_scripts/science_museum.py, src/cc_catalog_airflow/dags/provider_api_scripts/smithsonian.py, src/cc_catalog_airflow/dags/provider_api_scripts/staten_museum.py, src/cc_catalog_airflow/dags/provider_api_scripts/test_museum_victoria.py, src/cc_catalog_airflow/dags/provider_api_scripts/test_nypl.py, src/cc_catalog_airflow/dags/provider_api_scripts/walters_art_museum.py, src/cc_catalog_airflow/dags/provider_api_scripts/wikimedia_commons.py
Fixes #101 
This PR fixes the following problems with code quality in provider API scripts:
-  names shadowing built-ins (license)
-  variable that are used before they are declared
-  unused variables
-  unnecessary parentheses around tuples
This PR is a half of #67, split to make review easier. It also replaces #102 
=> Fix pep8 violations

src/cc_catalog_airflow/dags/common/urls.py
`urls.py` module validates license URLs that we save to the database.
`rewrite_redirected_url` function makes sure that we record the final license URL after any redirects. Currently, when called for all license URLs, it logs `{url_string} was rewritten to {rewritten_url}` even if the URL did not redirect, and, therefore, did not need rewriting. This can be confusing and fills the logs unnecessarily. 
This PR only logs rewritten URL if it is different from the URL passed to the function.
=> Remove logging of url rewriting when not rewritten

src/cc_catalog_airflow/dags/sync_commoncrawl_workflow.py
Fixes #117 
This PR adds default directory for commoncrawl tsvs if it is not set in the `OUTPUT_DIR` environment variable. This should prevent it from workflow loading error.
=> Set default output dir for commoncrawl

src/cc_catalog_airflow/dags/provider_api_scripts/test_wikimedia_commons.py, src/cc_catalog_airflow/dags/provider_api_scripts/wikimedia_commons.py
Fixes #107 
Remove 'File:' from the beginning and extension (eg. '.jpg') from the end of saved Wikimedia image titles. 
=> Clean Wikimedia item titles

src/cc_catalog_airflow/dags/provider_api_scripts/test_wikimedia_commons.py, src/cc_catalog_airflow/dags/provider_api_scripts/tests/resources/wikimedia/image_info_cc0.json, src/cc_catalog_airflow/dags/provider_api_scripts/wikimedia_commons.py
Fixes #105 
Wikimedia media items marked with CC0 or Public Domain do not have a licenseURL set in the API. Instead, their license information is sent in `extmetadata.LicenseShortName`. This PR checks for the value of this property to make sure public domain media items are also ingested.
=> Ingest wikimedia images marked with CC0 and PDM

src/cc_catalog_airflow/dags/util/loader/sql.py
Audio table did not have `watermarked` field at first. @krysal pointed out to me in a PR review that we have it in the API, and should have it in the catalog, as well. I added it to the `AudioStorage` and to loader sql scripts, but forgot to add it to the sql script that creates the intermediary loading table. This PR fixes this.
This PR is also another reason why we should abstract the database column creation and writing code so that we can add a column in one place, and it updates everywhere. Instead of having to add a column to more than three places.
=> Add missing `watermarked` column to audio loading table

src/cc_catalog_airflow/dags/common/__init__.py, src/cc_catalog_airflow/dags/common/licenses/licenses.py, src/cc_catalog_airflow/dags/common/licenses/test_licenses.py, src/cc_catalog_airflow/templates/README.md, src/cc_catalog_airflow/templates/create_api_script.py, src/cc_catalog_airflow/templates/template_provider.py_template, src/cc_catalog_airflow/templates/template_test.py_template, src/cc_catalog_airflow/templates/workflow.py_template
Fixes #92 
This script will make it easier for new contributors to add provider API scripts by giving them a Cookiecutter-like script for writing Provider API scripts. It creates the skeletons of the script, workflow file and tests. 
To run the script, create and activate a virtual environment, navigate to the templates folder and run it with provider name as a parameter:
```
cd src/cc_catalog_airflow/templates/
python3 create_api_script.py <provider_name>
```
This will create three files:
1. The API provider script with a skeleton implementation
2. The test file (blank)
3. The workflow file which doesn't really need much change, I suppose.
There are some instructions and a lot of #TODO comments in the file. 
This PR contains all the changes from #93, that I accidentally merged into …
=> Add a script to create provider API script template

src/cc_catalog_airflow/dags/provider_api_scripts/test_wikimedia_commons.py, src/cc_catalog_airflow/dags/provider_api_scripts/wikimedia_commons.py
In #66 we updated MediaStore class to accept an instance of 'LicenseInfo' class, which can derive all necessary license information, and validate it.
All Provider API scripts were updated to pass `license_info` to `MediaStore.add_item` method except for Wikimedia script. This PR replaces old `add_item` parameters(`license_url`) with the new `license_info`. It also updates the tests so that they would detect parameter mismatch in the future.
=> Make wikimedia script pass license_info, not license_url

.github/PULL_REQUEST_TEMPLATE.md
Targets WordPress/openverse#35
This PR adds a PR template to the repository.
=> Add a PR template to the repository

src/cc_catalog_airflow/docker-compose.yml
This fixes an issue where you could not run the API and the catalog at the same time due to conflicting postgres ports. This PR fixes the issue by changing the host port for the catalog postgres so that it no longer conflicts with the API postgres.
Checkout this branch and try running `dc up -d` for the catalog and the API together.
- [N/A] I added or updated tests for the changes I made (if applicable).
- [N/A] I added or updated documentation (if applicable).
<details>
```
Version 1.1
Suite D4700
San Francisco, …
```
=> Allow running the catalog and the API at the same time

openverse_catalog/templates/template_provider.py_template
The provider template builds a path for the test resources but it had the `provider` part not wrapped in a string, causing an error when you generate the template. This wraps it in a string to fix that.
Run the provider generation script according to the instructions in the README and verify that the test resource path is correct.
<details>
```
Version 1.1
Suite D4700 …
```
=> Fix resource path string in provider template

openverse_catalog/templates/template_test.py_template
This PR replaces `os.path` with `pathlib.Path` in path operations in the provider API script test templates. This makes them easier to read. There is an [interesting article by Trey Hunter](https://treyhunner.com/2019/01/no-really-pathlib-is-great/) about why `pathlib` is easier to use than `os.path`.
This PR also introduces a constant for a sample data file that is used multiple times in the tests.
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute verbatim …
```
=> Replace os.path with pathlib in provider API script template

README.md, justfile
Fixes #150  by @sarayourfriend 
Adds a `justfile` and updates the README to reference those scripts. This simplifies the README and the development process by moving repetative docker/docker-compose tasks into a command runner.
Install `just` and take some of the scripts for a spin and make sure they work.
<details>
```
Version 1.1
Suite D4700
Developer's Certificate of …
```
=> Add justfile with scripts and update README

README.md
This PR simply adds the airflow default username and password to the README, saving developers hours of google searching. Thanks for the idea @dhruvkb.
=> Update README.md with Airflow Credentials

.github/workflows/lint.yml, .github/workflows/push_pull_request_test.yml, justfile
Fixes #216 by @AetherUnbound
This PR uses the `setup-just` GitHub Action to allow us to use `just` in the CI workflows rather than explicit commands.
I also added a `just lint` recipe for running pre-commit on its own.
See if the build passes :grin: Alternatively, run `just lint` locally with your virtual environment activated.
<details>
```
Version 1.1
Suite D4700 …
```
=> Use `just` commands in CI workflow

.github/workflows/push_pull_request_test.yml, openverse_catalog/docker-compose.override.yml, openverse_catalog/docker-compose.yml
Fixes #212 by @AetherUnbound
This PR moves the `s3` and `postgres` services which are only used in development into the `docker-compose.overrides.yml`. Thanks to #153, running commands with the override file during the dev process is relatively easy. We cannot _remove_ services with an override file (only add or override). Production only needs one service and local development needs three, our new default is that the bare `docker-compose.yml` file is used for production, and the override file is used for local development. 
I've also updated the tests action use the appropriate docker-compose command for launching the test. This will be replaced with `just` in #216.
<details> …
=> Move dev-specific services into compose overrides file

docker/local_postgres/0004_openledger_image_view.sql, docker/local_postgres/0007_openledger_audio_view.sql
This PR addresses an issue I found on production wherein certain operations were failing because the matviews did not have unique keys:
```
[2021-11-01 23:28:36,188] {dbapi.py:204} INFO - Running statement: REFRESH MATERIALIZED VIEW CONCURRENTLY image_view;, parameters: None
[2021-11-01 23:28:37,190] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
File "/usr/local/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
self._prepare_and_execute_task_with_callbacks(context, task)
File "/usr/local/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
result = self._execute_task(context, task_copy)
File …
```
=> Add index creation for matviews

docker/airflow/Dockerfile, docker/airflow/entrypoint.sh, env.template, justfile, openverse_catalog/dags/common/slack.py, requirements_prod.txt, tests/dags/common/test_slack.py
Starts to tackle #214
This PR adds a `common.slack` module with a `SlackMessage` class and a simple `slack_message` function for sending slack messages into the #openverse-notifications channel. Examples for usage are provided in the docstring. Since we're using the `HttpHook` now, I've also added the `http` provider to our requirements, and removed the redundant provider requirements.
The Slack webhook also requires a connection, so I've added a spot for it in the `.env` file.
While doing the dev work for this, I also changed a few things around with the `just ipython` recipe. Running `ipython` really doesn't require the webserver to be running, so now it only depends on postgres and S3 (similar to the `test-session` recipe). It also mounts a local `.ipython` directory into the …
=> Slack alerting utilities

openverse_catalog/dags/common/loader/loader.py, openverse_catalog/dags/common/loader/operators.py, openverse_catalog/dags/common/loader/paths.py, openverse_catalog/dags/database/loader_workflow.py, tests/dags/common/loader/test_paths.py
This PR attempts to reduce the DAG complexity of the TSV loader by removing redundant steps & consolidating code.
TL;DR: Extra steps were present which were covered by Airflow functionality and have now been removed.
There were a number of steps in this DAG that were `DummyOperator`s (no-op steps). From what I could tell, the only purpose of these operators was to use Airflow's Trigger Rules[^1]. Incidentally, the same rules were also added to the actual operational tasks within the DAG, which ended up being a bit redundant. I've removed all of these no-op steps, and I've tried to make the logic a bit clearer (using the `doc_md` attribute for each task). The essence of these changes is:
* The table cleanup task will always run after the create table step (regardless of other failures) to …
=> Reduce TSV loader complexity

openverse_catalog/dags/common/requester.py, tests/dags/common/test_requester.py
Fixes ##291 by @AetherUnbound
This PR improves the error displayed by the `requester` object when a request fails due to authorization issues. I've also improved the tests that check exception handling by the requester; one test in particular was mocking an object that was never called and did not make an explicit check, so the test was passing even though it wasn't testing anything.
`just test`
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute verbatim …
```
=> Specific error message for auth errors on request, improve tests

openverse_catalog/dags/providers/jamendo_workflow.py
The Jamendo workflow takes longer than the default 30 minutes in production. This PR extends its timeout to 24 hours.
<details>
```
Version 1.1
Suite D4700 …
```
=> Extend Jamendo's timeout to 24 hours

docker/local_postgres/0007_openledger_audio_view.sql
This PR adds the DDL for the `audioset_view` table. This table is expected to exist in the catalog DB (see [the ingestion server data refresh for audio](https://github.com/WordPress/openverse-api/blob/a7aa53ffc5f9d3b8b6bebf9dbacba248623a5a61/ingestion_server/ingestion_server/tasks.py#L114)), but had no DDL associated with it. The DDL defined here originated from the [ingestion server's mock schemas](https://github.com/WordPress/openverse-api/blob/a7aa53ffc5f9d3b8b6bebf9dbacba248623a5a61/ingestion_server/test/mock_schemas/audioset_view.sql#L22).
I've initiated a data refresh for audio and it seems to have copied the data from this table over correctly!
1. `just db-shell`
1. `\d` -> should show `audioset_view`
[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git …
=> Add audioset_view to catalog DDL

openverse_catalog/dags/providers/provider_api_scripts/freesound.py, tests/dags/providers/provider_api_scripts/test_freesound.py
While trying to test the Freesound provider script locally, I encountered the following error:
```
[2022-01-17, 21:31:39 UTC] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
File "/usr/local/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
self._execute_task_with_callbacks(context)
File "/usr/local/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
result = self._execute_task(context, self.task)
File "/usr/local/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
result = execute_callable(context=context)
File "/usr/local/airflow/.local/lib/python3.9/site-packages/airflow/o …
```
=> Properly handle "None" values returned from Freesound API

openverse_catalog/dags/providers/provider_api_scripts/freesound.py, requirements_prod.txt, tests/dags/providers/provider_api_scripts/test_freesound.py
When running the Freesound provider API script, we kept getting the following error:
```python
Traceback (most recent call last):
File "/usr/local/airflow/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
httplib_response = self._make_request(
File "/usr/local/airflow/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
self._validate_conn(conn)
File "/usr/local/airflow/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
conn.connect()
File "/usr/local/airflow/.local/lib/python3.9/site-packages/urllib3/connection.py", line 416, in connect
self.sock = ssl_wrap_socket(
File "/usr/local/airflow/.local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket …
```
=> Freesound SSLError fix

README.md, docker-compose.override.yml
Fixes #338 by @AetherUnbound
This PR changes the default minio ports from `500X` to `501X` in an attempt to avoid using ports that Apple is reserving by default.
1. Run `just up`
1. Observe that minio binds to ports `5010` and `5011` rather than `5000` and `5001`
1. Go to http://localhost:5011 to view the minio console
<details>
```
Version 1.1
Suite D4700
Developer's …
```
=> Change minio ports from 500X to 501X

env.template, openverse_catalog/dags/common/slack.py
This PR adds a distinction between what could be set as an "alert" slack (when things go wrong) vs a "notification" slack message (updates on when things are going okay).
These Connections can be the same, but in order to have these messages go to different channels, they must operate under different webhooks in Slack.
1. Create two separate Slack webhooks.
1. Attempt to send messages via `common.slack` using both Connections.
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to …
```
=> Differentiate between slack channels

openverse_catalog/dags/common/dag_factory.py, openverse_catalog/dags/common/loader/loader.py, openverse_catalog/dags/common/loader/paths.py, openverse_catalog/dags/common/loader/s3.py, openverse_catalog/dags/common/loader/sql.py, openverse_catalog/dags/common/storage/media.py, openverse_catalog/dags/database/loader_workflow.py, openverse_catalog/dags/providers/freesound_workflow.py, openverse_catalog/dags/providers/jamendo_workflow.py, openverse_catalog/dags/providers/wikimedia_workflow.py, tests/dags/common/loader/test_s3.py, tests/dags/common/loader/test_sql.py, tests/dags/common/storage/test_audio.py, tests/dags/common/storage/test_media.py, tests/dags/common/test_dag_factory.py, tests/dags/common/test_resources/fake_provider_module.py
Fixes #285 by @AetherUnbound
At long last! This PR makes some significant changes to the TSV loading process.
**TL;DR**: The TSV loading steps are now connected within the provider workflow DAG and get triggered immediately after the provider finishes/fails.
**The long-winded description**:
The current TSV workflow is:
1. Provider workflow runs
1. TSV loader runs asynchronously every minute and ingests the oldest file
It is more desirable to have synchronous loading for the case where we're ingesting a resource daily/monthly for a few reasons:
- Running the TSV loader every minute results in a very large number of skipped runs (currently), see #309.
- If a problem occurs with a sheet, that sheet is moved to a different location and we have to hunt down the errant file. This also prevents …
=> Trigger TSV loading immediately after workflow

openverse_catalog/dags/common/dag_factory.py, openverse_catalog/dags/common/loader/loader.py, openverse_catalog/dags/common/loader/reporting.py, openverse_catalog/dags/common/loader/sql.py, openverse_catalog/dags/common/slack.py, tests/dags/common/loader/test_reporting.py, tests/dags/common/test_dag_factory.py, tests/dags/common/test_slack.py
Fixes #356 by @AetherUnbound 
This PR adds a Slack message that is triggered when TSV loading is completed for a particular provider. It does this by adding a new `report_load_completion` task which runs if the `load_from_s3` task completes successfully.
The message is logged to the Task log, and is also sent as a Slack message to the notifications channel if in the production environment (or if the `slack_message_override` env variable is turned on)
**Currently opened against #285 for ease of testing as it is dependent on those changes. Will be rebased onto main after #285 is merged.**
* The `pull_data` duration has a few sticking points:
* The `pull_data` task pulls all the data for _all media types_; there isn't a great way (as far as I can see) to determine how long it took to pull …
=> Add slack message on TSV load complete

openverse_catalog/dags/common/dag_factory.py, openverse_catalog/dags/providers/brooklyn_museum_workflow.py, openverse_catalog/dags/providers/finnish_museums_workflow.py, openverse_catalog/dags/providers/jamendo_workflow.py, openverse_catalog/dags/providers/museum_victoria_workflow.py, openverse_catalog/dags/providers/nypl_workflow.py, openverse_catalog/dags/providers/science_museum_workflow.py, openverse_catalog/dags/providers/smithsonian_workflow.py, openverse_catalog/dags/providers/statens_museum_workflow.py, openverse_catalog/dags/providers/walters_workflow.py
Fixes #348 by @AetherUnbound, fixes #349 by @AetherUnbound
This PR tweaks a few settings regarding task retries and timeouts for the typical ingestion DAGs. By "typical ingestion DAGs", I mean the dags that are run daily or monthly and ingest new data, either from a particular date range or for all of time.
Retries for all ingestion DAG related task have been reduced from 4 attempts total to 3. The time between retries has also been reduced from 15 minutes to 5 minutes.
Retries for the data pull steps have been disabled completely. This is to prevent cases where an ingestion fails, retries, gets to the same place (usually hours later) only to fail again. Failing immediately gives the subsequent loading steps the opportunity to ingest data that's already been collected, it notifies the …
=> Reconfigure retries & timeouts for typical ingestion DAGs

docker/airflow/Dockerfile, openverse_catalog/dags/commoncrawl/commoncrawl_etl.py, requirements_prod.txt
This PR updates Airflow to the latest version, v2.2.4. Unfortunately, this version does not yet support Python 3.10 (although that's happening soon! See: https://github.com/apache/airflow/issues/19059).
I've moved the Airflow version to an argument at the top of the Airflow installation section - this should make it easier to find and update the version, rather than hunting through the Dockerfile to try and find it.
This also fixes some deprecations warnings regarding Airflow that were appearing in the test output.
1. `just build`
1. `just test`
1. Run a DAG and verify that it works!
<details>
``` …
```
=> Update Airflow to 2.2.4

openverse_catalog/dags/common/slack.py, tests/dags/common/test_slack.py
Fixes #381
Adds the environment to the username in TSV loader Slack notifications and alerts. This allows us to distinguish between messages sent from production and ones sent from staging or local testing environments.
`just test`
Set `slack_message_override` environment variable to `true` in your local environment, and then run a provider workflow. Verify that the Slack notification sent on load_complete shows the environment (see screenshot above).
<details>
```
Version 1.1
Suite D4700 …
```
=> Report the environment in TSV loader Slack notifications

justfile, pytest.ini
Fixes #408
Adds `--dist=loadscope` to the `pytest.ini`. This tells `pytest-xdist` to [group tests by their class (for test methods) or module (for test functions)](https://pypi.org/project/pytest-xdist/#running-tests-across-multiple-cpus) when running tests across multiple workers. This makes it much easier to write complex tests without running into multithreading issues (see an example of this happening in #397, [comment](https://github.com/WordPress/openverse-catalog/pull/397#issuecomment-1067330351)).
`just test`
Try passing some args as well, eg:
`just test -k test_slack.py`
Bonus points you can verify that it solves the problem in #397 (check out that branch, apply these changes and observe that `just test` now passes reliably) …
=> Group test runs by module or class

openverse_catalog/dags/common/loader/sql.py, tests/dags/common/loader/test_sql.py
Fixes #388
Currently we have several provider DAGs that successfully pull data, but then fail in the `load_data` step due to duplicate keys on the direct `audio_url` or `image_url`, which must be unique. This PR attempts to add handling to the load_data task to avoid attempts to upsert these duplicates.
This must handle two basic cases (and the combination of the two):
* A record exists in the Catalog already with a particular `url`. We attempt to upsert a new record which has a **different** foreign identifier but the **same** url. (This new record should be ignored).
* A provider script returns multiple records with different foreign identifiers but the same url. We attempt to upsert all of these at the same time. (Only the first should be inserted).
See …
=> Handle duplicate keys in load_data task

openverse_catalog/dags/providers/provider_api_scripts/freesound.py, tests/dags/providers/provider_api_scripts/test_freesound.py
Fixes #389 by @stacimc
Similar to #330, this PR adds `ConnectionError` to the list of potentially flaky exceptions from Freesound that should be retried. These exceptions occur when attempting to get the file size for the previews, and aren't strictly necessary data to have. We've found that retrying with a delay fixes most of these occurrences. In cases where it does not, we exclude the file size information and continue iterating through the API.
I did a bit of refactoring to make this easier for us to change if we needed to down the line. Previously there were 3 locations we had to update to add a new exception, now there's only 1!
`just test`! (I love that that's a full sentence too :grin:)
[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commi …
=> Add ConnectionError to acceptable flaky exceptions for Freesound

openverse_catalog/dags/providers/provider_api_scripts/nypl.py, tests/dags/providers/provider_api_scripts/test_nypl.py
Fixes #401 by @AetherUnbound
This PR removes several `logger.warning` calls that were causing significant (and unnecessary) logging in the NYPL provider API script. I added the test before changing any of the provider script code to ensure parity with results before & after the changes. I also changed `type(...) == ...` calls to `isinstance`, since it is [faster and more accurate](https://switowski.com/blog/type-vs-isinstance).
`just test`! You should see the tests pass.
Optionally, run the NYPL DAG and observe that the `<x> not found due to <y>` error messages no longer appear.
<details>
```
Version …
```
=> Reduce noise in NYPL ingestion

openverse_catalog/dags/common/licenses/licenses.py, openverse_catalog/dags/providers/finnish_museums_workflow.py, openverse_catalog/dags/providers/provider_api_scripts/finnish_museums.py, tests/dags/providers/provider_api_scripts/test_finnish_museums.py
Fixes #392 by @stacimc
The Finnish Museum DAG's `pull_data` task was running without errors, but would eventually time out without having pulled any records (or logged any issues). It turns out this is because the API returns `license_url`s for each image linking to the Finnish version of the license _deed_, so like this:
```
http://creativecommons.org/licenses/by/4.0/deed.fi
```
instead of what our license validator logic expects, which is:
```
http://creativecommons.org/licenses/by/4.0
```
All the records were discarded as having an invalid license, so nothing got written to disk and the DAG appeared to be doing nothing.
This PR fixes the issue by removing the `deed.fi` suffix _within the provider script_. Initially I wanted to update the license validation logic to remove valid …
=> Fix invalid license urls from Finnish Museum API

docker-compose.override.yml, docker-compose.yml, env.template
Fixes #378 by @AetherUnbound
This PR modifies the primary and development docker-compose files to better utilize the published artifacts being produced by our CI/CD pipeline.
By default, local development will remain unchanged (although the tag of the image locally will change from `openverse-catalog:latest` to `ghcr.io/wordpress/openverse-catalog:latest`. In production, the docker-compose file will now attempt to pull the image from the GitHub container registry rather than build it. The version pulled from the container registry can be configured using the `DOCKER_IMAGE_TAG` environment variable (e.g. `v1.1.0`). This will allow us to pin versions during deployments rather than always pulling `latest`.
`just build` should run without changes and result in the new tag specified above. …
=> Use published Docker image in primary docker-compose.yml

openverse_catalog/dags/common/loader/reporting.py, tests/dags/common/loader/test_reporting.py
Fixes #373 by @zackkrida
This PR rounds the `duration` value for successful provider runs to 2 decimal places. These runs are usually on the order of minutes/hours/days, so we don't need more than centisecond resolution.
I also added some tests, which might be _a bit_ overkill, but it couldn't hurt :woman_shrugging:
```
*Provider*: `staten_museum`
*Media Type*: `image`
*Number of Records Upserted*: 46102
*Duration of data pull task*: 162.36981462899894
* _Duration includes time taken to pull data of all media types._
```
```
*Provider*: `staten_museum`
*Media Type*: `image`
*Number of Records Upserted*: 46102
*Duration of data pull task*: 162.37
* _Duration includes time taken to pull data of all media types._
```
`just test`
Optionally, run the Staten Museum DAG to completion (should …
=> Round duration for provider ingestion completion message

openverse_catalog/dags/common/licenses/licenses.py
Fixes #419 by @AetherUnbound
This PR adds an `lru_cache` to `is_valid_license_info`, which gets called once per every record during provider ingestion.
Here's a performance test you can run!
**Before cache**
1. Check out `main`
2. Run `just ipython`
3. Paste the following into a cell and hit enter:
```python
import random
from common import licenses
from common.licenses.constants import get_license_path_map
license_map = get_license_path_map()
sample_list = random.choices(list(license_map.keys()), k=10_000)
sample_licenses = [
licenses.LicenseInfo(license="x", version="y", url=url, raw_url="z")
for url in sample_list
]
sample_licenses += [
licenses.LicenseInfo(license="x", version="y", url=(url[5:] + url[:5]), raw_url="z")
for url in sample_list
]
random.shuffle(sample_licenses)
```
4. …
=> Add LRU cache to `is_valid_license_info`

openverse_catalog/dags/providers/phylopic_workflow.py, openverse_catalog/dags/providers/provider_api_scripts/phylopic.py, tests/dags/providers/provider_api_scripts/test_phylopic.py
Fixes #410 by @AetherUnbound
This PR makes a number of changes to the PhyloPic provider script to allow it to process records over the course of a week.
The previous implementation would specify a _start date_, but not an _end date_. This meant that, if a DAG for a given day were re-run, it would process all data since that date until now (rather than all data updated on that day).
This PR now uses the [from **and** to options available in the PhyloPic API](http://phylopic.org/api/#method-image-time-range) in order to construct an immutable date range. This will ensure that re-runs of a particular DAG will always process data for the same date range.
I've also made some changes to support moving this from an `@daily` to an `@weekly` schedule interval. The processed date range will be 7 …
=> Change PhyloPic date range & schedule interval

openverse_catalog/dags/common/loader/reporting.py, openverse_catalog/dags/common/provider_dag_factory.py, tests/dags/common/loader/test_reporting.py
Fixes #375 by @stacimc
Currently a Slack notification is sent every time a `load_data` task completes in a provider DAG. For DAGs with multiple media types, this means multiple notifications get sent (eg for Wikimedia Commons, you'll see a message for `audio` and one for `image`).
This PR consolidates those messages into a single notification per provider DAG, which reports information for all of the media types. A single `report_load_completion` task is triggered on `ALL_DONE`, meaning that all upstream tasks are in the `success`, `failed`, `upstream_failed`, or `skipped` states.
Here's what the DAG graph looks like (example is Wikimedia Commons to show multiple media types):
1. This means that if the `load_data` task for one media type succeeds, but a second errors and has to be …
=> Send single slack notification per provider on TSV load complete

openverse_catalog/dags/providers/provider_api_scripts/wikimedia_commons.py, tests/dags/providers/provider_api_scripts/test_wikimedia_commons.py
Fixes #436 by @stacimc
This PR increases the scope of error handling within the Wikimedia Commons provider script to handle cases where there is no audio metadata.
While I couldn't get the exact case that happened in production, I was able to reproduce the error by removing the `"audio"` section of one of our test files:
```
$ pytest -n 1 -k test_wikimedia
Test session starts (platform: linux, Python 3.9.7, pytest 6.2.5, pytest-sugar 0.9.4)
rootdir: /usr/local/airflow, configfile: pytest.ini
plugins: raises-0.11, xdist-2.5.0, mock-3.6.1, anyio-3.5.0, forked-1.4.0, flaky-3.7.0, sugar-0.9.4
gw0 [35]lecting ... 
tests/dags/providers/provider_api_scripts/test_wikimedia_commons.py ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓ …
```
=> Handle case where Wikimedia has no audio metadata

.github/workflows/ci_cd.yml, docker/local_postgres/Dockerfile
This PR fixes an issue that cropped up spontaneously on the CI for our main branch: https://github.com/WordPress/openverse-catalog/runs/5740531711?check_suite_focus=true
Upon investigating, it appeared postgres was failing to start during testing due to the following error:
```
initdb: error: invalid locale settings; check LANG and LC_* environment variables
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.
```
While attempting to resolve this issue, I noticed some odd things happening in the `apt` steps of the Postgres Docker image. Namely:
* Postgres was being updated to 13.6 (from the 13.2 present in our base image)
* Locales _were_ being generated
Looking into this more, I found a GitHub issue that exactly …
=> Remove `apt upgrade` from PG image, upgrade to 13.6

openverse_catalog/dags/data_refresh/dag_factory.py
Fixes #447 by @AetherUnbound 
The `data_refresh` DAGs are currently timing out after one hour of the `wait_for_completion` step, while we ping the ingestion server for the status of the data refresh. The problem was that the task was not in `reschedule` mode, so it would not free the slot after an unsuccessful ping. This caused it to timeout on its lower `execution_timeout` rather than the `timeout`. ([Relevant docs](https://airflow.apache.org/docs/apache-airflow/stable/concepts/tasks.html#timeouts))
This PR:
* Sets the `wait_for_completion` task into reschedule mode. Now it will timeout only if a single attempt at poking takes longer than the `execution_timeout` of 1hr, or if no poke is successful before the `timeout`
* Updates `timeout` to 3 days instead of the default 1 week. **Looking …
=> Adjust timeouts for Data Refresh `wait_for_completion` step

openverse_catalog/dags/common/urls.py, pytest.ini, requirements_dev.txt, tests/dags/common/conftest.py, tests/dags/common/loader/test_smithsonian_unit_codes.py, tests/dags/common/sensors/test_single_run_external_dags_sensor.py, tests/dags/common/test_urls.py, tests/dags/conftest.py
Fixes #342 by @AetherUnbound
This PR re-introduces pytest-socket, which ensures that tests don't attempt to reach out to services via a socket unless explicitly allowed. 
In attempting to uncover which tests were failing with pytest-socket, I found that the license URL validation [makes a request to Creative Commons to ensure the URL is accurate](https://github.com/WordPress/openverse-catalog/blob/main/openverse_catalog/dags/common/urls.py#L65). This was the cause of almost all of our external accessing and was used internally by many tests across the codebase. The only way to mock it in its current form is to auto-use a global fixture that mocks all `request.get` calls, which has undesirable side effects for other tests. So I opted to alias `requests.get` within that module specifically, …
=> Re-introduce pytest-socket

openverse_catalog/dags/common/loader/loader.py, openverse_catalog/dags/common/loader/reporting.py, openverse_catalog/dags/common/loader/sql.py, openverse_catalog/dags/common/provider_dag_factory.py, tests/dags/common/loader/test_reporting.py
Fixes #411 by @stacimc
Dependent on #434
This PR adds some count collecting throughout the ingestion process so that we can better track the number of duplicates encountered for a given provider + media type. While we currently handle duplicates thanks to #395, we would still like some reporting on this (that way we can look into providers that have high rates of duplicates).
The test functions for these changes are a little unorthodox; I wanted to to test the message generated by multiple media types and make sure that they don't interfere with each other. If the functions are confusing or could use more comments, let me know!
I also added type hints in a few different places to make it easier for us down the road to understand what's happening, especially since the …
=> Show duplicate record count in completion slack message

docker-compose.override.yml
Fixes #457 by @sarayourfriend
This PR changes the restart policy for local development so that the webserver does not attempt to start on system restart.
Here's the output of `docker-compose config` (local development):
```yaml
webserver:
build:
args:
REQUIREMENTS_FILE: requirements_dev.txt
context: /home/aether/git-a8c/openverse-catalog
dockerfile: docker/airflow/Dockerfile
command: init
depends_on:
postgres:
condition: service_started
s3:
condition: service_started
environment:
...
image: ghcr.io/wordpress/openverse-catalog:latest
ports:
- published: 9090
target: 8080
restart: on-failure
volumes:
- /home/aether/git-a8c/openverse-catalog/openverse_catalog:/usr/local/airflow/openverse_catalog:rw
- /home/aether/git-a8c/openverse-catalog/openverse_catalog/dags:/usr/local/airflow/openverse_ca …
```
=> Change docker-compose restart policy for local development

openverse_catalog/dags/common/storage/columns.py, openverse_catalog/dags/providers/provider_api_scripts/freesound.py
Fixes #454 by @krysal
This PR changes the upsert strategy of the `alt_files` column from a typical `merge_json_objects` strategy to a `merge_json_arrays` one. This ensures that upserts will not duplicate the alt file records that exist within the array.
I also fixed a small issue with the date range formatting for Freesound.
**Note**: To remove existing duplicates, we'll also need to run the following command:
```sql
UPDATE audio
SET alt_files = (
SELECT jsonb_agg(DISTINCT x)
FROM jsonb_array_elements(audio.alt_files) y(x)  -- the y(x) is some postgres black magic called a "lateral join"
);
```
<details> <summary>Example</summary> 
```sql
openledger> select distinct jsonb_array_length(alt_files) as num_alt_files from audio;
+---------------+
| num_alt_files |
|---------------|
| 2 …
```
=> Fix `alt_files` duplicates

openverse_catalog/dags/providers/provider_api_scripts/wikimedia_commons.py, tests/dags/providers/provider_api_scripts/test_wikimedia_commons.py
Fixes #445 by @AetherUnbound
This PR catches a case where an invalid bit rate is provided by the Wikimedia API. The integer maximum for postgres is 2<sup>32</sup>/2, since it's unsigned.
`just test`
Optionally:
1. `just up`
1. `just shell`
1. Run `airflow dags trigger -e 2022-03-26 wikimedia_commons_workflow`
1. Enable the Wikimedia DAG in the UI
1. Let it run until completion 
1. Open Minio on localhost:5011
1. Navigate to the `openverse-storage/audio/wikimedia_commons` prefix and download the produced TSV
1. Open the TSV and check that the line referenced in #445 now has `\N` instead of its original bitrate
<details>
``` …
```
=> Wikimedia: Catch bit rates that are greater than the int max

docker/airflow/entrypoint.sh, env.template, openverse_catalog/dags/data_refresh/dag_factory.py
Fixes #433 by @AetherUnbound 
Makes the airflow connection environment variables a little easier to read and maintain, by handling the url encoding and https:// prepending automagically where necessary.
@AetherUnbound  wrote great testing instructions here: https://github.com/WordPress/openverse-catalog/issues/433#issuecomment-1074446931 
The only (probably obvious) thing I would add is that after running `just dotenv`, I needed to manually edit `.env` to try out various values with "AIRFLOW_CONN_DATA_REFRESH=" rather than "not_set".
Here are my results:
<details>
```
Version 1.1
Copyright (C) 2004, …
```
=> Make Airflow connection variables easier to read

openverse_catalog/dags/common/loader/reporting.py, openverse_catalog/dags/providers/provider_api_scripts/brooklyn_museum.py, tests/dags/common/loader/test_reporting.py
Fixes https://github.com/WordPress/openverse-catalog/issues/476 by @AetherUnbound 
There was a test for a specific piece of metadata, but when there is no data to load, the detailed metadata don't apply and aren't generated. So we needed a slightly more expansive check for nothing. In testing, I found another place where a very similar issue comes up, and put in some code for that. 
The original issue has great instructions for replicating. It's a little tricky, because you have to have a situation where there isn't any data to load, and providers are always(ish) adding data. 🥇 Also, I _think_ that if you just put in a future date in the airflow test command, things  get deadlocked. But this morning (4/22/2022) I did `airflow dags test brooklyn_museum_workflow 2022-04-22` and rather than …
=> Enable reporting when there is no data to load

env.template, openverse_catalog/dags/common/popularity/sql.py
Fixes #448 by @AetherUnbound 
Most of the time when we want to recalculate popularity data, we use the `refresh_audio_view_data` DAG to refresh the matview with popularity data, and once a month we run `refresh_all_audio_popularity_data` to recalculate popularity entirely. This workflow works to update data for newly ingested images and pick up things like new popularity metrics.
If new SQL code is deployed for the popularity calculations though, it's necessary to drop the existing matviews and functions and recreate them. We use the `recreate_audio_popularity_calculation` DAG to do this.
The `recreate_audio_popularity_calculation` DAG removes the views in its first step, including both the `audio_view` and the dependent `audioset_view`: …
=> Recreate the audioset matview after full popularity recalculation

openverse_catalog/dags/common/loader/reporting.py, tests/dags/common/loader/test_reporting.py
Fixes https://github.com/WordPress/openverse-catalog/issues/497 by @AetherUnbound
Adds a text description "less than 1 sec" for duration under one second, and an automated test case with a duration of 0.1 seconds.
This is a small enough change that getting the branch and running `just test` ought to do it. 
<details>
```
Version 1.1
Suite D4700
Developer's Certificate of …
```
=> Add human readable description for durations under 1 second

tests/dags/common/sensors/test_single_run_external_dags_sensor.py
The tests for `SingleRunExternalDAGsSensor` remove all pools and reinstate the default pool during test cleanup. The consequence is that when you run `just test` locally, any custom pools that you have defined in your local Airflow are wiped. This is specifically annoying because we have a custom `data_refresh` pool used for the data refresh DAGs, so it must be re-added every time you run tests locally.
This PR just updates the tests to make sure we only clean up the specific test pool created in the file.
* Add a new pool through the Admin > Pools menu (or http://localhost:9090/pool/add). Make sure to save.
* Run `just test`
* Refresh the pools list in Airflow and verify your pools are still there 🎉 
[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project …
=> Don't delete custom pools during test cleanup

openverse_catalog/dags/providers/provider_api_scripts/smithsonian.py, tests/dags/providers/provider_api_scripts/test_smithsonian.py
Fixes #504 by @stacimc 
The Smithsonian provider script uses a list of sub-providers to map records to their sources. Before attempting to pull data, the provider script compares its own sub-provider list with the list of active sub-providers from the API, and alerts if there is a mismatch. Unfortunately this API appears to be flaky and sometimes returns an empty list of unit codes, so the Smithsonian script fails immediately and suggests that we should delete all of our subproviders 🥲 
This PR just adds a retry that detects when we get an empty list of codes from the API and tries again up to 3 times.
This is _very flaky_ and cannot be reliably reproduced, but at minimum you can make sure the happy path still works by simply running the Smithsonian provider script a few times locally …
=> Retry flaky request when Smithsonian provider script detects no unit codes

docker/airflow/Dockerfile
Fixes #512 by @AetherUnbound
Adds the DAGs folder to the PYTHONPATH within the Docker container.
Per #512, run:
1. `just shell`
1. `python -c "from common import storage"`
1. Observe that no `ModuleNotFoundError` exception is raised.
<details>
```
Version 1.1
Suite D4700
(a) The …
```
=> airflow dockerfile: set `PYTHONPATH` to DAGs folder

tests/dags/common/conftest.py, tests/dags/common/loader/test_s3.py, tests/dags/common/loader/test_sql.py
Fixes #343 by @AetherUnbound
This PR unconditionally destroys S3 buckets used during testing. The previous fix (#344) would only remove the bucket _if_ it had files. We've added some tests since then that request a bucket but don't end up actually loading files into them (this occurs during test parametrization where it's easier to request everything for all load functions rather than set up individualized parameters). Example:
https://github.com/WordPress/openverse-catalog/blob/9dca8963cda9436b4b9674804116e855afb62a39/tests/dags/common/loader/test_sql.py#L208
Now, buckets will always be destroyed no matter what.
I've also fixed some slight issues I noticed during testing. In one case we were handing in the _bucket object_ itself when we should have been using the name, and that was …
=> Unconditionally destroy buckets after testing

openverse_catalog/dags/providers/provider_api_scripts/cleveland_museum_of_art.py, tests/dags/providers/provider_api_scripts/test_cleveland_museum_of_art.py
I can't seem to find it now 😄, but I'm certain I saw an error reported somewhere from the Cleveland museum DAG of the form:
`AttributeError: 'NoneType' object has no attribute 'status'`
Cleveland provider script will throw an AttributeError if the response is `None`, because we attempt to check the response status _before_ checking that the response itself is not `None`.
`just test` and verify the new test passes.
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and …
```
=> Correct order of None handling in Cleveland provider script

openverse_catalog/dags/common/extensions.py, openverse_catalog/dags/common/storage/image.py, openverse_catalog/dags/common/storage/media.py, tests/dags/common/storage/test_media.py, tests/dags/common/test_extensions.py
Related to #536 by @obulat
This PR extracts the function to get an extension (`filetype`) from the media URL. It also adds `filetype` validation to make sure that we use a single variant of the `filetype`s that have several valid variants: `jpg` for `jpeg/jpg` and `tiff` for `tif/tiff`.
This PR is the basis for the other data normalization PRs, and it is tested there :)
<details>
```
Version 1.1
Suite D4700
license …
```
=> Add a helper function to extract extension from the media URL

openverse_catalog/dags/common/urls.py, tests/dags/common/test_urls.py
Fixes #531 by [krysal](https://github.com/krysal)
It adds a flag to allow the stripping of leading and trailing slash in the `validate_url_string` method present in `openverse_catalog/dags/common/urls.py`. Flag defaults to `True` in case it is not provided. 
Added a test case `test_validate_url_string_keeps_trailing_slash` present in `tests/dags/common/test_urls.py`. You may verify if it passes by using the `just test -k url` command. 
<details>
```
Version 1.1
Suite D4700
Everyone is …
```
=> Add flag to strip slash in urls while validating

openverse_catalog/dags/providers/provider_api_scripts/smk.py, tests/dags/providers/provider_api_scripts/resources/smk/expected_image_data_hq.json, tests/dags/providers/provider_api_scripts/resources/smk/expected_image_data_legacy.json, tests/dags/providers/provider_api_scripts/resources/smk/expected_image_data_partial.json, tests/dags/providers/provider_api_scripts/test_smk.py
Related to #536 by @obulat 
This PR adds `filetype` and `filesize` to the list of data collected from the SMK API.
The tests for the script should pass.
<details>
```
Version 1.1
Suite D4700
have the right to submit …
```
=> Add `filetype` and `filesize` to SMK script

docker/local_postgres/0007_openledger_audio_view.sql, openverse_catalog/dags/common/popularity/sql.py
Fixes #263 by @dhruvkb 
This PR adds `audio_set_foreign_identifier` to the materialized view, extracting the id from the `audio_set` JSONB column similar to how it's done in the API:
https://github.com/WordPress/openverse-api/blob/32f5a2166b879d45298a2eb97d430e5fed426903/load_sample_data.sh#L76-L77.
If you don't have any audio data locally, run one of the audio provider DAGs to get some audio locally. Then, run the `recreate_audio_popularity_calculation` DAG. After it finishes its run, you should see the `audio_set_foreign_identifier` column in the `audio_view` materialized view before the last column with correct values.
I'm not sure where I can add the tests for this change.  …
=> Add audio_set_foreign_identifier to the audio materialized view

openverse_catalog/dags/common/provider_dag_factory.py, openverse_catalog/dags/common/storage/media.py, openverse_catalog/dags/common/storage/util.py, openverse_catalog/dags/providers/provider_api_scripts/cleveland_museum.py, openverse_catalog/dags/providers/provider_api_scripts/provider_data_ingester.py, openverse_catalog/dags/providers/provider_dag_factory.py, openverse_catalog/dags/providers/provider_ingestion_workflow_dag_factory.py, openverse_catalog/dags/providers/provider_workflow_dag_factory.py, openverse_catalog/dags/providers/provider_workflows.py, openverse_catalog/templates/workflow.py_template, tests/dags/common/storage/test_image.py, tests/dags/common/storage/test_media.py, tests/dags/common/storage/test_util.py, tests/dags/common/test_provider_dag_factory.py, tests/dags/providers/provider_api_scripts/resources/clevelandmuseum/expected_batch_data.json, tests/dags/providers/provider_api_scripts/resources/clevelandmuseum/image_type_print.json, tests/dags/providers/provider_api_scripts/resources/clevelandmuseum/image_type_web.json, tests/dags/providers/provider_api_scripts/resources/provider_data_ingester/complete_response.json, tests/dags/providers/provider_api_scripts/resources/provider_data_ingester/mock_provider_data_ingester.py, tests/dags/providers/provider_api_scripts/test_cleveland_museum.py, tests/dags/providers/provider_api_scripts/test_provider_data_ingester.py
Fixes #229, fixes #248
This PR adds an abstract `ProviderDataIngester` class which encapsulates the `DelayedRequester` and `MediaStore` objects needed for a provider script, and pulls out reusable code for requesting and processing batches of records. It also refactors the Cleveland Museum provider script to use the new class, as a simple initial example.
In doing so it attempts to accomplish a couple things:
* Delays the creation of `DelayedRequester` and `MediaStore` objects until the DAG actually _runs_, rather than creating expensive objects at import time. This is discussed in #229 
* Attempts to pull out as much reusable code as possible, related to making and processing requests. The goal is for individual provider scripts to only need to provide code for API-specific handling, and …
=> Add base class for Provider API scripts

openverse_catalog/dags/providers/provider_dag_factory.py, openverse_catalog/dags/providers/provider_workflows.py
Fixes #380 by @AetherUnbound 
This PR turns on `catchup` for dated DAGs, which will result in the backfilling of data since their `start_date`. This is necessary to backfill data for the time that the provider scripts were turned off. It is only necessary for dated DAGs because all other DAGs ingest all the data from their provider on each run, rather than the data for the current day.
The start date was previously set to `01-01-1970` by default. It's obviously not necessary to schedule DagRuns for that far back, so I've also updated the start_dates to tighten the date range:
* **Wikimedia Commons**: _September 2004_, when it was [launched](https://commons.wikimedia.org/wiki/Commons:Welcome)
* **Flickr**: _February 2004_, when it was [launched](https://www.britannica.com/topic/Flickrcom) …
=> Turn on catchup for dated DAGs to allow backfill

.github/workflows/ci_cd.yml, README.md, openverse_catalog/dags/common/loader/sql.py, tests/conftest.py, tests/dags/providers/test_provider_dag_factory.py
This addresses an issue identified by @rwidom as part of #549: Previously, our `pull_data` tasks would either succeed or fail, it was not possible for them to be skipped (even if they didn't pull any data). Now that we're introducing pre-ingestion tasks, it's possible that upstream tasks might skip the rest of the workflow. In these cases, the `create_table` step was skipped successfully, but the `delete_table`'s trigger rules were setup such that it was unconditionally run. This would then cause issues where it would try to delete a table that did not exist (see [here](https://github.com/WordPress/openverse-catalog/pull/549#discussion_r930949202)).
This PR adds an `IF EXISTS` clause to the drop table SQL to ensure that, even if the create table step doesn't run, the unconditionally run …
=> Only drop load table if it exists

openverse_catalog/dags/providers/factory_utils.py, openverse_catalog/dags/providers/provider_dag_factory.py, tests/dags/providers/test_factory_utils.py
Fixes #449 by @AetherUnbound
This PR adds some additional logic to the provider DAG factory which includes date information in the S3 prefix for the generated TSV. The prefix includes year, month, and day (the latter two fields are conditional on how frequently the DAG is run). 
The function added in `factory_utils.py` is added as a [`user_defined_macro`](https://airflow.apache.org/docs/apache-airflow/1.10.12/tutorial.html?highlight=user_defined_macros#templating-with-jinja) to the DAG. This allows it to be used as a Jinja macro within templated parameters similar to [those available by default with Airflow](https://airflow.apache.org/docs/apache-airflow/stable/templates-ref.html). Its call pattern is similar to our `XCOM_PULL_TEMPLATE` setup. The end result is that the generated S3 key …
=> Partition TSVs by date

openverse_catalog/dags/common/loader/provider_details.py, openverse_catalog/dags/common/storage/image.py, openverse_catalog/dags/common/storage/media.py, openverse_catalog/dags/providers/provider_api_scripts/flickr.py, openverse_catalog/dags/providers/provider_api_scripts/stocksnap.py, tests/dags/common/storage/test_media.py, tests/dags/providers/provider_api_scripts/test_stocksnap.py
Fixes #292 by @dhruvkb
This PR adds a default `category` to media items in the `MediaStore`'s `clean_media_metadata` method.
With this change, this is how `category` for an item is determined:
- if a _provider script_ can assign different categories, it should set the item category in the `get_record_data` method (or when calling `add_item` with old scripts).
- `MediaStore` uses the `category` value a provider script passes.
-  If the `category` is `None`, `MediaStore` tries to add the category that is default for provider, and is listed in `provider_details.py` module.
Run one of the data collection DAGs until you see `Wrote 100 lines to the disc` in the `Pull data` task log. Stop the DAG. Wait a couple of seconds until the DAG finishes, and then check the data in the database (I use …
=> Use the default provider categories during ingestion

tests/dags/common/sensors/test_single_run_external_dags_sensor.py
Fixes a testing issue identified by @stacimc
After the merging of #636, it appeared that our tests were failing on `main`. Further investigation showed that tests would run fine synchronously (e.g. `just test -n 1`) but would fail then run in parallel. I was able to track this down to the `test_single_run_external_dags_sensor.py` tests, which were deleting all `DagRun`s and `TaskInstances` as part of setup/teardown. This PR changes those deletions to match a specific DAG prefix, which is used when creating DAGs throughout the test.
`just test` should be sufficient.
<details>
```
Version 1.1
Copyright …
```
=> Only delete dag runs/task instances during testing that match pattern

.github/workflows/ci_cd.yml, DAGs.md, README.md, justfile, openverse_catalog/dags/data_refresh/dag_factory.py, openverse_catalog/dags/maintenance/airflow_log_cleanup_workflow.py, openverse_catalog/utilities/README.md, openverse_catalog/utilities/dag_doc_gen/DAGs.md, openverse_catalog/utilities/dag_doc_gen/dag_doc_generation.py, tests/utilities/dag_doc_gen/test_dag_doc_generation.py
Fixes #189 by @AetherUnbound
This PR adds a utility script which will automatically generate DAG documentation based on DAG attributes, provider workflow information, and individual DAG documentation. I added a `just` recipe along with the script so it can be run easily.
I also added a GitHub Actions step which will fail if the DAG documentation has changed but the auto-generated doc was not updated. Ideally we would have this as part of a pre-commit check or similar, but due to the nature of the DAG parsing, this script must be run within the Docker container. Doing so during pre-commit checks would be too much overhead (IMO).
See [DAGs.md](https://github.com/WordPress/openverse-catalog/blob/3761387897570aec203e5632698534bba4a01edc/DAGs.md) for the current output!
**Example output**: …
=> Automatic DAG documentation generation

openverse_catalog/dags/common/licenses/licenses.py, openverse_catalog/dags/common/requester.py, openverse_catalog/dags/common/storage/columns.py, openverse_catalog/dags/common/tsv_cleaner.py, openverse_catalog/dags/common/urls.py, openverse_catalog/dags/providers/provider_api_scripts/brooklyn_museum.py, openverse_catalog/dags/providers/provider_api_scripts/europeana.py, openverse_catalog/dags/providers/provider_api_scripts/flickr.py, openverse_catalog/dags/providers/provider_api_scripts/nypl.py, openverse_catalog/dags/providers/provider_api_scripts/provider_data_ingester.py, openverse_catalog/dags/providers/provider_api_scripts/rawpixel.py, openverse_catalog/dags/providers/provider_api_scripts/smk.py, openverse_catalog/dags/providers/provider_api_scripts/wordpress.py, tests/dags/common/test_urls.py, tests/dags/providers/provider_api_scripts/test_provider_data_ingester.py
- Use more specific exceptions when catching errors
- Use and catch a specific retries-exceeded exception
- Return total values committed by all stores
- Clean up comments
- Add unittest for failure mode
Fixes #366 by @AetherUnbound
This PR ensures that the results within the media store always get written to disk, including when Airflow issues a `SIGTERM` to the worker tasks. There are a lot of small changes in this PR, but they all fall into two categories:
1. Making exception handling _where we're expected to continue execution_ more specific
2. Wrap the `ingest_records` function of the provider data ingester steps in a `try`/`finally` to ensure that records in the stores' buffers will be written to disk.
One thing I notice when trying to test this out was that when I marked an …
=> Tighten exception handling, always flush buffer

openverse_catalog/dags/providers/factory_utils.py, openverse_catalog/dags/providers/provider_api_scripts/cleveland_museum.py, openverse_catalog/dags/providers/provider_api_scripts/provider_data_ingester.py, openverse_catalog/dags/providers/provider_dag_factory.py, tests/dags/providers/provider_api_scripts/test_provider_data_ingester.py, tests/dags/providers/test_factory_utils.py
Fixes #367 by @AetherUnbound 
_Problem_
If a provider workflow encounters errors during the `pull_data` step, the task will fail and any partial data that was collected will be loaded. To resume ingestion, the DAG must be manually re-reun, and because the ingestion task has no context for the previous run, it will re-process all of the data from the API from the very beginning. This can be very time consuming!
_A note about alternative solutions_
I attempted several strategies for allowing the `pull_data` task to _retry_, picking up from the last set of query parameters. This goes against the philosophy of Airflow, which expects tasks to be idempotent. Ultimately, even if we were willing to slightly misuse Airflow in this way, I think it would be very difficult if not impossible. For …
=> Add configuration options to skip ingestion errors

docker/local_postgres/0007_openledger_audio_view.sql, openverse_catalog/dags/common/popularity/sql.py
Fixes #658 by @stacimc
_Please see #658 for extended context._
This PR alters the `audioset_view` to select records which are distinct on `foreign_identifier` & `provider`, using the most recently updated record as the source of truth. This prevents cases where some records which share `audio_set` information actually have different values within the JSONB body. Since this circumvents the previous `SELECT DISTINCT` clause, we were seeing errors in the data refresh due to violated unique key constraints.
The original issue arises from the fact that `audioset_view` is a `VIEW` (not a table or materialized view) that pulls information from the `audio.audio_set` JSONB column. Since `audio.audio_set` is not indexed, there are no constraints on the data within them. With Freesound, we got into …
=> Update audioset_view to use most recently updated f_id/provider pair

openverse_catalog/dags/providers/factory_utils.py, tests/dags/common/operators/test_postgres_result.py, tests/dags/providers/test_factory_utils.py, tests/dags/providers/test_provider_dag_factory.py
This addresses a comment left by @sarayourfriend in https://github.com/WordPress/openverse-catalog/pull/632#discussion_r934777831
This PR standardizes all uses of a `datetime` or `datetime` related object/class on the standard library's `datetime` module rather than `pendulum`. Pendulum is a library that Airflow uses internally, but we don't specify it explicitly in our requirements. Additionally, the related `pendulum` analogs to `datetime` are actually subclasses of `datetime` objects, so it's perfectly safe to use the base classes everywhere as well.
`just test` should be sufficient!
<details>
``` …
```
=> Standardize on datetime over pendulum

openverse_catalog/dags/common/slack.py, openverse_catalog/dags/maintenance/check_silenced_dags/check_silenced_dags.py, tests/dags/common/test_slack.py, tests/dags/maintenance/test_check_silenced_dags.py
Fast follow from  #643 to implement a suggestion by @sarayourfriend 
⚠️ Because this introduces a breaking change to the configuration variable, we must make sure the variable is not configured in production before merging. If it is configured, we need to make sure no affected DAGs (`check_silenced_dags`, any silenced DAGs) are running while we deploy these changes and update the variable interface. [Discussion](https://github.com/WordPress/openverse-catalog/pull/654#issuecomment-1212176723).  ⚠️ 
#643 introduced an Airflow variable (`silenced_slack_alerts`) that allows configuring a DAG to skip Slack reporting of errors. The implementation in that PR only allows for skipping Slack reporting for _all_ error messages, but in reality we're unlikely to want this behavior. It's much safer to …
=> Allow DAGs to silence only errors matching predicate

openverse_catalog/dags/providers/factory_utils.py, tests/dags/providers/test_factory_utils.py
Fixes #692 by @AetherUnbound
This PR wraps the run function in a try/finally block so that the duration is always recorded & pushed. I'm not removing the machinery which expects that duration _could_ be `None` because there may still be circumstances where Airflow kills things even in the `finally` block or if the error occurs before that block.
`just test`
Optionally, you could start a provider DAG and fail the data pull task after it starts actually saving data to disk. When viewing the logs for the `report_load_completion` task, the crafted message should still show a duration even though the upstream task failed.
<details>
``` …
```
=> Always record provider run duration

justfile
#623 by @AetherUnbound
Forcing the `AIRFLOW_VAR_INGESTION_LIMIT` to 1mil so that all tests pass
<details>
```
Version 1.1
Suite D4700
indicated in the file; …
```
=> hardcodes the test ingestion limit to 1 000 000

openverse_catalog/dags/providers/provider_api_scripts/brooklyn_museum.py, openverse_catalog/dags/providers/provider_api_scripts/provider_data_ingester.py, openverse_catalog/dags/providers/provider_workflows.py, tests/dags/providers/provider_api_scripts/resources/brooklynmuseum/expected_metadata.json, tests/dags/providers/provider_api_scripts/test_brooklyn_museum.py, tests/dags/providers/provider_api_scripts/test_provider_data_ingester.py
Fixes #583 by @stacimc
This PR refactors the Brooklyn Museum provider API script to use the provider data ingester. The changes here are straightforward, mostly just moving things into static methods and removing the extra machinery that's covered by the provider data ingester base class.
I also consolidated the tests a bit so we didn't have to repeat the test cases.
As part of this change, I made a change to the `ProviderDataIngester` base class's `get_response_json` method. Since this function is a wrapper around the delayed requester, it felt easier to augment this than to access the requester directly. This accomplishes a similar task to what @obulat did in https://github.com/WordPress/openverse-catalog/pull/630#discussion_r950515494. i also removed the `typing` module from the …
=> Refactor Brooklyn Museum to use ProviderDataIngester

openverse_catalog/dags/providers/provider_api_scripts/jamendo.py, tests/dags/providers/provider_api_scripts/test_jamendo.py
Fixes #667 by @stacimc
This PR alters the logic for determining which URL to use for Jamendo audio results. Ingestions now always use the "streaming" URL rather than the "download" URL. Our primary use-case for the `url` column presently is to provide an audio file that the frontend can stream as a preview. Preferring the download URL was causing some issues on the frontend, see https://github.com/WordPress/openverse-frontend/issues/1605. 
As part of the API response we get back a `from` parameter that looks like the API or some other encoded information. Since we're already stripping `trackid` from a URL in another portion of the provider script, I opted to consolidate this logic and keep the original `_remove_<field>` functions around as a means for holding documentation specific to …
=> Always use Jamendo's "streaming" audio

openverse_catalog/dags/common/slack.py, tests/dags/common/test_slack.py
Fixes #693 by @AetherUnbound
This PR allows strings to be passed in as the exception to an `on_failure_callback`.
See #693 for a longer description of the problem.
`just test`
Optionally attempt to fail a provider pull media task locally. You should see the failure callback still logged (instead of an exception). Here's an example, with extra logging added at the beginning to emphasise what was handed in:
```
[2022-08-24, 03:43:25 UTC] {slack.py:308} ERROR - exception='task marked as failed externally' type(exception)=<class 'str'>
[2022-08-24, 03:43:25 UTC] {slack.py:227} INFO - 
*DAG*: `cleveland_museum_workflow`
*Task*: `pull_image_data`
*Execution Date*: 2022-07-01T00:00:00Z
*Log*: http://localhost:8080/log?execution_date=2022-07-01T00%3A00%3A00%2B00%3A00&task_id=pull_image_data&dag_id …
```
=> Allow string as exceptions in `on_failure_callback`

openverse_catalog/dags/common/storage/audio.py, openverse_catalog/dags/common/storage/image.py, openverse_catalog/dags/providers/provider_api_scripts/provider_data_ingester.py, openverse_catalog/dags/providers/provider_api_scripts/wikimedia_commons.py, openverse_catalog/dags/providers/provider_workflows.py, tests/dags/providers/provider_api_scripts/resources/wikimedia/audio_filedata_ogg.json, tests/dags/providers/provider_api_scripts/resources/wikimedia/audio_filedata_wav.json, tests/dags/providers/provider_api_scripts/test_wikimedia_commons.py
Fixes #598 by @stacimc 
Refactors Wikimedia Commons to use the ProviderDataIngester base class
For Wikimedia Commons, the `batch_limit` applies to the number of `image_pages` to process, which is not necessarily a 1:1 relationship with records ingested. The result is that using a global `ingestion_limit` still works to limit the processing time but you may see slightly more records ingested.
Run the Wikimedia Commons DAG. Also try setting an `ingestion_limit`
<details>
```
Version 1.1
Suite D4700
San Francisco, CA, …
```
=> Refactor Wikimedia Commons to use ProviderDataIngester

openverse_catalog/dags/providers/provider_api_scripts/provider_data_ingester.py, tests/dags/providers/provider_api_scripts/test_cleveland_museum.py, tests/dags/providers/provider_api_scripts/test_provider_data_ingester.py
Fixes #703 by @AetherUnbound 
TL;DR: this PR removes error swallowing during `get_batch`, which I believe was only necessary in _legacy code_ in provider scripts that were not making use of updates to the `DelayedRequester`. It also updates some tests.
When the `ProviderDataIngester` was first implemented, I included error handling that I noticed in many of our provider scripts during the `get_batch` logic, and in particular in Cleveland (which was the first provider I happened to refactor). Cleveland, in fact, explicitly tests that errors/None responses are caught.
After auditing our provider scripts to understand why that handling was there in the first place, I believe all of this can be removed. The try/except is (or was, before refactoring) present in exactly half of our provider …
=> Remove error swallowing during ingestion

openverse_catalog/dags/providers/provider_api_scripts/cleveland_museum.py, tests/dags/providers/provider_api_scripts/test_cleveland_museum.py
This error was hit in a recent Cleveland Dag run:
```
File "/usr/local/airflow/openverse_catalog/dags/providers/provider_api_scripts/cleveland_museum.py", line 76, in _get_image_type
if keyed_image := image_data.get(key):
AttributeError: 'NoneType' object has no attribute 'get'
```
We already handle the situation where `images` is not available in the response, but if it is explicitly set to `None` then `_get_image_type` is called with None. This PR just adds a check and a new test.
`just test`.
You can also try running Cleveland locally with the query params that were being run when the error was hit in production. Manually trigger with this dagrun conf:
```
{"initial_query_params": {"cc": "1", "has_image": "1", "limit": 1000, "skip": 16000}}
```
It's sufficient to make sure it gets past …
=> Add none check for Cleveland `image_data`

.pre-commit-config.yaml, dag-sync.sh, docker/airflow/entrypoint.sh, tests/dags/providers/provider_api_scripts/resources/wikimedia/prettify.sh
Related to WordPress/openverse#289
adding shellcheck to openverse-catalog repo
=> Add spellcheck to pre-commit config

.github/workflows/ci_cd.yml, DAGs.md, docker-compose.override.yml, docker/airflow/Dockerfile, env.template, justfile, openverse_catalog/dags/commoncrawl/commoncrawl_etl.py, openverse_catalog/dags/commoncrawl/sync_commoncrawl_workflow.py, openverse_catalog/dags/data_refresh/dag_factory.py, openverse_catalog/dags/data_refresh/data_refresh_types.py, openverse_catalog/dags/database/image_expiration_workflow.py, openverse_catalog/dags/database/loader_workflow.py, openverse_catalog/dags/database/recreate_popularity_calculation_dag_factory.py, openverse_catalog/dags/database/report_pending_reported_media.py, openverse_catalog/dags/maintenance/airflow_log_cleanup_workflow.py, openverse_catalog/dags/maintenance/check_silenced_dags.py, openverse_catalog/dags/maintenance/pr_review_reminders/pr_review_reminders_dag.py, openverse_catalog/dags/oauth2/authorize_dag.py, openverse_catalog/dags/oauth2/token_refresh_dag.py, openverse_catalog/dags/providers/factory_utils.py, openverse_catalog/dags/providers/provider_dag_factory.py, openverse_catalog/utilities/dag_doc_gen/dag_doc_generation.py, pytest.ini, requirements_prod.txt, tests/dags/common/operators/test_postgres_result.py, tests/dags/common/sensors/test_single_run_external_dags_sensor.py, tests/dags/providers/test_factory_utils.py, tests/utilities/dag_doc_gen/test_dag_doc_generation.py
Fixes #732 by @AetherUnbound
This also addresses some security issues that dependabot identified.
This PR updates our Airflow version to 2.4.0. I've also borrowed the pattern set up in #656 and applied it to the Airflow version, so we only have to update it in one place now!
As part of the version update, I've also updated the [`schedule_interval` parameter to be `schedule` instead](https://airflow.apache.org/docs/apache-airflow/2.4.0/release_notes.html#deprecation-of-schedule-interval-and-timetable-arguments-25410). What's unfortunate however is that the `airflow.models.dag.Dag` model _does not_ have a `schedule` attribute, you still must use `schedule_interval` when referencing it on the DAG object. So there are a few instances where we were not able to update that value.
I added a …
=> Bump Airflow to 2.4.0, standardize version bump process

openverse_catalog/dags/common/slack.py, tests/dags/common/test_slack.py
Recent provider DAG errors have caused notifications containing images to be sent to Slack. @sarayourfriend pointed out that while these messages have historically been harmless, it's possible that this could happen with NSFW content.
This PR updates our Catalog Slack utility to **not unfurl links or media** by default.
Go through the current uses of `send_message` and `send_alert` and verify that there are no use cases where we _definitely want_ media and/or links to be unfurled.
For further manual testing, I'm not sure how to force a Slack message with an image 🤔
<details>
```
Version 1.1
Copyright …
```
=> Default unfurling of links and media to False in Slack notifications

.github/dependabot.yml, justfile, requirements.txt, requirements_tooling.txt
Fixes #371 by @zackkrida
This PR adds a dependabot configuration to the repository.
Based on my understanding of the [dependabot documentation](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file), I believe dependabot will only try to update _pinned dependencies_. We only pin dependencies in cases where the dependency itself is not defined in the [Airflow constraints file](https://airflow.apache.org/docs/apache-airflow/stable/installation/installing-from-pypi.html#constraints-files). As such I think it should be safe to have dependabot manage the _pinned_ dependencies, since those ones aren't managed by Airflow! I'm not sure how best to test this, we may just need to merge it and find out :smile: Dependabot …
=> Add dependabot config

openverse_catalog/dags/common/licenses/licenses.py, openverse_catalog/dags/common/requester.py, openverse_catalog/dags/common/urls.py, openverse_catalog/dags/providers/provider_api_scripts/modules/etlMods.py, openverse_catalog/dags/providers/provider_api_scripts/rawpixel.py
Fixes #760 by @AetherUnbound
As per the Issue description, there are instances where URLs will not render properly when they occur at the end of a sentence when a period follows the URL. Periods after URLS have been removed at the following locations:
[openverse-catalog/openverse_catalog/dags/common/requester.py](https://github.com/WordPress/openverse-catalog/blob/0072114ea479b378a94e1144340935023acbdf3d/openverse_catalog/dags/common/requester.py#L85)
Line 85
`logger.error(f"Error with the request for URL: {url}.")`
[openverse-catalog/openverse_catalog/dags/common/requester.py](https://github.com/WordPress/openverse-catalog/blob/0072114ea479b378a94e1144340935023acbdf3d/openverse_catalog/dags/common/requester.py#L69-L72)
Lines 69 to 72
`logger.warning( 
f"Unable to request URL: …
=> Remove periods after URLs in log lines.

openverse_catalog/dags/common/requester.py, openverse_catalog/dags/providers/provider_api_scripts/provider_data_ingester.py, openverse_catalog/dags/providers/provider_api_scripts/stocksnap.py, tests/dags/common/test_requester.py, tests/dags/providers/provider_api_scripts/test_stocksnap.py
Fixes #758 and fixes #759 by @AetherUnbound 
Returns `{}` instead of `None` for next query params, since the increment goes in the url rather than parameters but `None` will stop the ingestion. 
Adds a User-Agent to the stocksnap provider header, and sets up `DelayedRequester` to use `ProviderDataIngester.headers` by default.
Try running the stocksnap DAG locally, observe no errors and some data. Try running a couple of other API DAGs as well. I tried Cleveland Museum and it went well.
I added tests for the requester, but wasn't 100% sure the best way to do that for `ProviderDataIngester`, and if it would really be necessary. 
<details>
<summary>Developer Certificate of …
=> Add user agent to StockSnap header and use header in requests by default

openverse_catalog/dags/common/loader/reporting.py
I added some disclosure text to the `load_completion` Slack message for reingestion workflows which is meant to be in italics, but left off the closing `_` character:
This PR just fixes the italics :) 
This should be straightforward, but if you want to test this manually you need to run the `wikimedia_reingestion_workflow`.
Reingestion workflows take a long time to run, so I'd recommend first updating Wikimedia's configuration in `provider_reingestion_workflows.py` to reduce the number of reingestion days. Example:
```
ProviderReingestionWorkflow(
dag_id="wikimedia_reingestion_workflow",
<...>
daily_list_length=2,
),
```
Then set an `ingestion_limit` Airflow variable to a small number of records (eg `100`), and run the `wikimedia_reingestion_workflow`. …
=> Fix italics for duration disclosure

.github/dependabot.yml
This PR increases the allowable number of open dependabot PRs to 10. [The default is 5 open PRs](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#open-pull-requests-limit). Since we haven't had dependabot enabled on this repo before, there are a number of dependencies that need updating. Presently, we are having to run the dependabot check manually if we don't want to wait until the scheduled run next month once we hit our 5 PR quota.
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The Linux Foundation and its …
```
=> Increase dependabot PR limit to 10

.github/workflows/actionlint.yml, .github/workflows/ci_cd.yml
Related to [openverse #267](https://github.com/WordPress/openverse/issues/267#issue-1288144556) by @sarayourfriend 
This pull request Adds concurrency settings for workflow
<details>
```
Version 1.1
Suite D4700
have …
```
=> Add concurrency settings for workflow

openverse_catalog/dags/common/constants.py
Fixes #774 by @AetherUnbound
This PR disables email on failure when using the `DAG_DEFAULT_ARGS`. Those defaults include a Slack exception on-failure-callback which is sufficient for alerting the team. Email on failure is still the global Airflow default, so DAGs which do not use the `DAG_DEFAULT_ARGS` will still have some failure conveyance mechanism.
Launch the stack and check the DAG details for any DAG which uses the DAG default args to ensure `email_on_failure` is `False`. 
<details>
```
Version 1.1
Suite D4700 …
```
=> Disable email on failure by default

DAGs.md, openverse_catalog/dags/providers/provider_api_scripts/freesound.py, openverse_catalog/dags/providers/provider_workflows.py, tests/dags/providers/provider_api_scripts/test_freesound.py
Fixes #586 by @stacimc
This PR refactors the Freesound provider script to use the `ProviderDataIngester` class.
It's a pretty standard refactor, aside from some more unique functions that have additional retries built in.
One thing I noticed is that the original provider script is set up to allow processing a subset of data, but it has been run in such a way that it consumes the entire dataset. I think this is fine for now, but **as soon as we have a full, successful run**, this should be turned into a daily dated DAG. This will be a much more efficient way to run the DAG! Getting a successful run will require some additional error handling for failures that have occurred in the past, which I'm hoping to enumerate in another ticket.
1. `just recreate && just test`
1. Run the DAG locally …
=> Refactor Freesound to use ProviderDataIngester

openverse_catalog/dags/providers/provider_api_scripts/provider_data_ingester.py, tests/dags/providers/provider_api_scripts/test_provider_data_ingester.py
Fixes #[issue number] by @[issue author]
This is necessary pre-requisite work for refactoring Flickr (#585)
Some of our provider ingesters iterate over a set of query params and call `ingest_records` for each. For example:
```python
def ingest_records(self, **kwargs):
for building in BUILDINGS:
logger.info(f"Obtaining images of building {building}")
super().ingest_records(building=building)
```
This causes a problem with `ingestion_limit`, an Airflow variable intended to restrict the number of records ingested (to speed up testing). Reaching the ingestion limit causes `ingest_records` to return early, but for DAGs like the above that call `ingest_records` multiple times, you'll have to hit the `ingestion_limit` _once for every run of `ingest_records`_.
This PR just updates the …
=> Respect the ingestion limit if ingest_records is called multiple times

DAGs.md, openverse_catalog/dags/common/slack.py, openverse_catalog/dags/maintenance/check_silenced_dags.py, openverse_catalog/dags/providers/provider_api_scripts/provider_data_ingester.py, openverse_catalog/dags/providers/provider_api_scripts/wikimedia_commons.py, tests/dags/common/test_slack.py
Fixes #605 by @AetherUnbound
- Standardize the following Airflow Variable names to uppercase: `slack_message_override, silenced_slack_notifications, environment, ingestion_limit`
- Update the references to the lower case Variables mentioned that appear within documentation.
Run `just test`
<details>
```
Version 1.1
Suite D4700
By making …
```
=> Standardize Airflow Variable names to uppercase

env.template, openverse_catalog/dags/common/constants.py
Modified the DAG_DEFAULT_ARGS dictionary's retries record and added the DEFAULT_RETRY_COUNT to 2 in env.template file and reformatted both files according to flake8
Fixes #675  by @AetherUnbound 
I fixed this issue by adding the environment variable for the retries in env.template and fetching the same variable in constants.py file using os.getenv(<variable-name>). 
Not Applicable
<details>
```
Version 1.1
Suite D4700 …
```
=> Allow default retry count to be determined by environment variable

dag-sync.sh
Fixes #785 785 by @AetherUnbound 
This PR gets the last git log and checks if have files inside the `dags` folder to notify slack. 
<details>
```
Version 1.1
Suite D4700
have the right to submit it under the open …
```
=> Add condition to not notify slack when don't have files in dags folder

DAGs.md, openverse_catalog/dags/providers/provider_reingestion_workflows.py
Fixes #616 by @stacimc
Adds a reingestion workflow for Metropolitan.
* For the configuration of reingestion days, I copied the configuration from Wikimedia. This is the existing configuration with the fewest number of nodes, so it feels like a reasonable first-attempt that can be reconfigured later.
* The Metropolitan API has an 80 request per second rate limit. Historically, most DagRuns complete very quickly (<30 minutes), with a few outliers at ~5hrs and ~9.5hrs. **I've set the initial max_active_tasks to 2, which should respect the rate limit while giving the DAG better odds of succeeding within 24 hours.**
There is an edge case in the ingestion limit logic which causes Metropolitan to ignore limits, so make sure you have #818 locally if you want to set a LIMIT. You can also manually …
=> Add reingestion workflow for Metropolitan

openverse_catalog/dags/providers/provider_api_scripts/provider_data_ingester.py, tests/dags/providers/provider_api_scripts/test_provider_data_ingester.py
I think this should fix the final big edge case with ingestion limit :)
Before this PR, when an INGESTION_LIMIT was set in a provider script, we would cap the `batch_limit` to that value, and then check if the limit was exceeded _after each call to `process_batch`_. This leaves an edge case when a provider doesn't pass `batch_limit` to their API, and may get back huge batches that are larger than our limit.
This PR adds one extra check for the `ingestion_limit`, inside `process_batch` itself. Now we will halt processing even within a batch when the limit is reached.
Metropolitan is a good example of the buggy behavior. You can observe the bug in action by setting an `INGESTION_LIMIT` Airflow variable to `100` locally and running `metropolitan_workflow`. You'll see that it appears to …
=> Respect ingestion limit in process_batch

DAGs.md, openverse_catalog/dags/providers/provider_reingestion_workflows.py
Fixes #[issue number] by @[issue author]
In a previous PR (#819) I updated the `ProviderReingestionWorkflow` to automatically generate the `dag_id` from the provider script filename, rather than explicitly defining it in each dataclass. Unfortunately I did not notice that Wikimedia's reingestion workflow was custom. It should be `wikimedia_reingestion_workflow` rather than the generated `wikimedia_commons_reingestion_workflow`. Since the DAG has a new id it is disabled and has no history in production.
We can fix this by restoring the old DAG id. Fortunately this is already supported by the dataclass.
`just test`
`just up` and verify that the DAG is named `wikimedia_reingestion_workflow` in your local env.
[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Pr …
=> Restore the old dag_id for wikimedia_reingestion_workflow

openverse_catalog/dags/providers/provider_api_scripts/phylopic.py, openverse_catalog/dags/providers/provider_api_scripts/wordpress.py, openverse_catalog/dags/providers/provider_workflows.py, tests/dags/providers/provider_api_scripts/test_wordpress.py
Fixes #599 by @stacimc
This PR refactors the WordPress Photo Directory provider script to use the `ProviderDataIngester` class. Since this was one of our more recent provider additions, it was already fairly closely aligned with our general layout now! I removed all of the boilerplate functions the class now handles, and most of the remaining functions did not need significant updates.
1. `just test`
2. Run the workflow locally and ensure that data gets inserted into the catalog.
<details>
```
Version 1.1
Suite …
```
=> Refactor WordPress to use `ProviderDataIngester`

DAGs.md, openverse_catalog/dags/providers/provider_reingestion_workflows.py
Fixes #617 by @stacimc 
Now that all blockers are resolved, we can add a reingestion workflow for Phylopic! With the most recent changes to Phylopic in its refactor (#747), it is now a straightforward dated DAG and we can wire up a reingestion workflow with the same minimal configuration as Metropolitan.
I've chosen the same conf options as described in #819.
```just test```
Set an INGESTION_LIMIT to something small and run `phylopic_reingestion_workflow` locally 😄 
<details>
```
Version 1.1
Suite D4700
San …
```
=> Add reingestion DAG for Phylopic

openverse_catalog/dags/providers/provider_api_scripts/europeana.py, openverse_catalog/dags/providers/provider_reingestion_workflows.py, openverse_catalog/dags/providers/provider_workflows.py, tests/dags/providers/provider_api_scripts/resources/europeana/europeana_example.json, tests/dags/providers/provider_api_scripts/resources/europeana/europeana_image_list.json, tests/dags/providers/provider_api_scripts/resources/europeana/image_data_example.json, tests/dags/providers/provider_api_scripts/test_europeana.py
This PR addresses a number of items with Europeana. I'm happy to split this out into multiple PRs if that would be most warranted, but all of the commits are focused on Europeana so this seemed easiest.
1. Fixed API responses
2. Updated the start date of the daily DAG
3. Updated the reingestion DAG
After testing this DAG after the merge of #821, I noticed that we were receiving no data for the run. The logs had `Request failed with success = "False"` in each of the data pull tasks. After some investigation, it appeared that the value for `success` that we were receiving was actually the Python/JSON native `true`, rather than `"True"`. @stacimc mentioned that she was able to test the DAG successfully while the PR was being reviewed. It looks like this was because the initial check for …
=> Fix Europeana success test, activate reingestion workflows

DAGs.md, openverse_catalog/dags/providers/factory_utils.py, openverse_catalog/dags/providers/provider_dag_factory.py, openverse_catalog/dags/providers/provider_reingestion_workflows.py, openverse_catalog/dags/providers/provider_workflows.py, openverse_catalog/docs/adding_a_new_provider.md, tests/dags/providers/test_factory_utils.py, tests/dags/providers/test_provider_dag_factory.py
Fixes #824 by @AetherUnbound 
* Removes now-unused logic branches that handled legacy provider scripts
* Updates the ProviderWorkflow and ProviderReingestionWorkflow dataclasses to infer the provider script, provider name, and media types from the configured ingestion class
* This means that to configure a new DAG, *all* you need to define in the dataclass is the Ingester class! Everything else is optional
* Updates some docs
**Note: #848 should be merged first and this will need to be rebased to pull in Europeana changes.**
Not included:
It may be time to revisit the `generate_tsv_filenames` logic, which I have not touched in this PR beyond deleting fully-unused legacy branches. Should we open a new issue for this?
```just test```
Test some DAGs! Make sure to try at least one audio-only, …
=> Remove legacy provider DAG logic

openverse_catalog/dags/providers/provider_api_scripts/cleveland_museum.py, tests/dags/providers/provider_api_scripts/test_cleveland_museum.py
Fixes https://github.com/WordPress/openverse-catalog/issues/825 by @AetherUnbound
This PR removes the default empty string assignment to metadata, while extracting metadata fields from input data object.
So that all the None value fields would be filtered out at the second to last line of the _get_metadata function, resulting in only metadata fields which has info.
<details>
```
Version 1.1
Suite D4700
license document, but …
```
=> Filter out the extra fields with no additional info in Cleveland Museum metadata

openverse_catalog/dags/common/storage/audio.py, openverse_catalog/dags/common/storage/image.py, openverse_catalog/dags/common/storage/media.py, tests/dags/common/storage/test_audio.py, tests/dags/common/storage/test_media.py
Fixes #729 by @stacimc 
Removes two unused arguments, `output_dir` and `output_file` from MediaStore as well as cleaning up any references and tests that use the function to function properly.
- Open PR locally
- Run `just test` to run the test suite
- Verify all tests pass
=> Remove unused arguments in MediaStore

openverse_catalog/dags/providers/provider_api_scripts/science_museum.py, tests/dags/providers/provider_api_scripts/test_science_museum.py
Fixes #864 by @obulat 
Overriding `get_should_continue` to terminate the pagination when we reach the end of the results.
I wanted to use a test like:
```
def test_get_should_continue():
params = {**default_params, "page[size]": 1} # updating the default params to reduce the response size
first_page_json = sm.get_response_json(params)
last_page_number = first_page_json.get("meta", {}).get("total_pages", 1) - 1
params["page[number]"] = last_page_number - 1
_, should_continue = sm.get_batch(params)
params["page[number]"] = last_page_number
_, should_not_continue = sm.get_batch(params)
assert should_continue is True
assert should_not_continue is False
```
But because I wasn't using a mocked ingester, the code was actually trying to call the api.
So, I looked at other places that test …
=> Override `get_should_continue` for science museum ingester

dag-sync.sh
PR #871 recently got reported to our Slack channel when it was deployed, even though it doesn't have any change to operational DAG code. This appears to be because we were only searching for `/dags/` in the path string, and that _also_ includes changes to DAG tests only. This PR changes the DAG sync messaging so it only reports after changes to actual operational DAG code are deployed.
Merge and see!
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute verbatim …
```
=> Only report DAG sync when DAG files have changed

docker/local_postgres/0007_openledger_audio_view.sql, justfile, openverse_catalog/dags/common/popularity/sql.py, tests/dags/common/popularity/test_sql.py
This is a follow up to #795 which adds the Rawpixel popularity metric to the python logic steps. It was added to the DDL as part of #795, but it was not added to the table itself and said table gets updated in Python as part of the image popularity constant recalculation step once monthly. Even if it was added directly to the table, it wouldn't get updated if it were adjusted later down the line.
I also added a test which ensures that each of the values defined in the python logic are present in the DDL, and vice versa. This actually identified that Freesound was missing from the DDL, which I added in this PR.
We can either add Rawpixel's metric to the table directly after this, or we can wait until the next full popularity recalculation.
⚠️  **After merging this PR one of the above …
=> Add Rawpixel to image popularity recalculation logic

DAGs.md, openverse_catalog/dags/providers/factory_utils.py, openverse_catalog/dags/providers/provider_api_scripts/provider_data_ingester.py, openverse_catalog/dags/providers/provider_api_scripts/science_museum.py, openverse_catalog/dags/providers/provider_api_scripts/wikimedia_commons.py, tests/dags/providers/provider_api_scripts/test_science_museum.py, tests/dags/providers/test_factory_utils.py
Fixes #864
The Science Museum API appears to be throwing 400 errors when you attempt to access a page number greater than 50 for large datasets, even when there should legitimately be > 50 pages. For example, a recent run received this response for the 50th page of a dataset:
```
"links":{
"self":"https://collection.sciencemuseumgroup.org.uk/search/date[from]/1875/date[to]/1900/images/image_license?page[size]=100&page[number]=50",
"first":"https://collection.sciencemuseumgroup.org.uk/search/date[from]/1875/date[to]/1900/images/image_license?page[size]=100",
"last":"https://collection.sciencemuseumgroup.org.uk/search/date[from]/1875/date[to]/1900/images/image_license?page[size]=100&page[number]=65",
"prev":"https://collection.sciencemuseumgroup.org.uk/search/date[from]/1875/date[to]/1900/im …
```
=> Handle Science Museum errors with batches larger than 50 pages

.github/workflows/ci_cd.yml
Fixes #909 by @krysal 
The PR replaces the command by writing to the environment file as suggested by GitHub.
Wait to see if the `ci_cd.yml` workflow passess.
- [N/A] I added or updated documentation (if applicable).
<details>
```
Version 1.1
Suite D4700 …
```
=> Replace deprecated `set-output` command

openverse_catalog/dags/providers/provider_api_scripts/provider_data_ingester.py, tests/dags/providers/provider_api_scripts/test_provider_data_ingester.py
Adds an option to the DagRun conf to let you override the `date` of a run of a dated provider DAG.
When you manually run a dated DAG, it is always passed in today's date. This option allows you to pass in any arbitrary date you'd like. While I don't necessarily expect this to be used frequently in production, it has come in handy many times for local testing.
To trigger a DAG using a date override, select the `Trigger DAG w/ config` option seen here:
Then pass your chosen date in using a `YYYY-MM-DD` format like this:
```{"date": "2022-04-10"}```
Pick a dated DAG, like Europeana:
* Try running it normally by enabling the DAG locally and letting a scheduled run start. Verify that it correctly uses the scheduled date.
* Try running it **manually** without a DagRun conf. Verify that it uses …
=> Allow overriding the date from the DagRun conf

openverse_catalog/dags/providers/provider_api_scripts/wordpress.py, tests/dags/providers/provider_api_scripts/test_wordpress.py
Fixes #853 by @AetherUnbound 
The WordPress Photo Directory DAG was failing to halt ingestion gracefully when it reached the end of its data. Instead, it raises a 400 when attempting to access a page number beyond the total page count. This is especially bad if `skip_ingestion_errors` is enabled, because it will retry infinitely.
To fix this we need to make a HEAD request to get the total page count. This information is only available in the headers and not `response_json`, so we are not able to fetch it in `get_batch_data`. This PR makes this additional request on the first batch, and then halts ingestion during `get_should_continue` when we reach the final page.
At the time this PR was written, this DAG detects 53 pages of results. To test it locally, I recommend editing the initial …
=> Halt ingestion when WordPress Photo Directory reaches last page

openverse_catalog/dags/common/loader/loader.py, openverse_catalog/dags/common/loader/provider_details.py, openverse_catalog/dags/common/loader/sql.py, openverse_catalog/dags/providers/provider_dag_factory.py, openverse_catalog/dags/providers/provider_workflows.py, tests/dags/common/loader/test_loader.py, tests/dags/common/loader/test_sql.py
Fixes #800 by @AetherUnbound 
We've noticed some very strange duplicate reporting from the Smithsonian provider on a few DagRuns:
The bug is caused when the `load_from_s3` step retries (see investigation described in my comment [here](https://github.com/WordPress/openverse-catalog/issues/800#issuecomment-1343610886)). Essentially, at the moment the `load_from_s3` step does three things:
1. Loads all of the pulled data from s3 into a temporary `load_table`
2. Runs some cleanup steps on the data, which among other things **deletes rows that have duplicated foreign ids**
3. Upserts the remaining data to the catalog DB
The bug happens when the `load_from_s3` step successfully does step 1 & 2, but then errors or times out during the upsert. When the task retries, _all three steps_ are …
=> Break load_from_s3 into separate tasks to fix duplicate reporting

openverse_catalog/dags/providers/provider_api_scripts/science_museum.py, tests/dags/providers/provider_api_scripts/test_science_museum.py
We received an error during a recent run of the Science Museum DAG:
```
Request https://collection.sciencemuseumgroup.org.uk/search/date[from]/1935/date[to]/1945/images/image_license?page[size]=100&page[number]=50 contains more than 50 pages of data and cannot be fully ingested. Reduce the size of the year range in order to complete ingestion.
```
We're currently needing to split Science Museum ingestion up into small sections by date ranges, to circumvent an issue where we receive unexpected results when querying a dataset larger than 50 pages. The above error message was added to warn us when one of our year ranges exceeds 50 pages, so that we can decrease the range.
For this PR, I did a quick audit of the page count for each of our existing year ranges and adjusted _all_ of them to …
=> Adjust year ranges for Science Museum

DAGs.md, openverse_catalog/dags/providers/provider_api_scripts/freesound.py, tests/dags/providers/provider_api_scripts/test_freesound.py
Fixes #659
Sometimes Freesound returns a 404 when trying to fetch audio_set information. In a production run with `skip_ingestion_errors` enabled, we encountered this problem only for a single audio set (https://freesound.org/apiv2/packs/35596/). However since the task timed out (and some batches are skipped), it's possible the error would have been encountered additional times in a truly full run.
This PR:
* moves the token from query params into the headers
* skips errors when trying to fetch an audio_set
When an error happens fetching audio set info, I opted to **return `None` for the set id & name and just continue**. Another option would be to discard the record.
* We already have three retries when fetching audio_set information. Since we've had trouble with flakiness, I've left the …
=> Handle Freesound 404s when fetching audio sets

openverse_catalog/dags/common/github.py, openverse_catalog/dags/maintenance/pr_review_reminders/pr_review_reminders_dag.py, requirements_dev.txt, tests/dags/common/test_github.py
Fixes #936 by @AetherUnbound
This PR modifies the `_make_request` function to prevent an exception from being raised when GitHub returns an HTTP 204 `No Content` response. This is done on comment deletion responses: https://docs.github.com/en/rest/pulls/comments?apiVersion=2022-11-28#delete-a-review-comment-for-a-pull-request. I suspect this case hadn't happened yet since this was introduced in #642, which is why these only just started raising errors.
In addition to the change necessary to fix the underlying issue (9a1a9920b330647684db9bd9a86477e7d4acfa39), I also changed the `Variable.get` calls at the top level in accordance with a discussion from #925 and #904 (46ad685cf8dcbe0df708f9a57739fb26c04861a0).
In order to test this I added the `pook` library, which @sarayourfriend added to …
=> Allow no content responses from GitHub

openverse_catalog/dags/maintenance/check_silenced_dags.py
Follow up to #688 and #937, this moves the last top-level `Variable.get` call into a template so that we are no longer performing `Variable` retrievals during DAG parse time (but rather waiting until runtime to perform the value retrieval).
1. Ensure that the DAG runs fine locally
1. (Optional) check that the task's "Rendered Template" shows the GitHub PAT value correctly interpolated into the `op_kwargs`
errors.
<details>
```
Version 1.1
Suite D4700
San Francisco, CA, …
```
=> Defer retrieval of GitHub API key to runtime

openverse_catalog/dags/providers/provider_api_scripts/finnish_museums.py, tests/dags/providers/provider_api_scripts/test_finnish_museums.py
Fixes #913 
#913 is low priority because it just tracks optimizing the DAG for days with small amounts of data. Since the DAG is now also raising errors for days with very large amounts (see 12-16-22), I'm increasing the PR to high priority.
In #879 I split the ingestion of data for the Finnish DAG into 48 half-hour increments over the ingestion day. This attempts to avoid some buggy behavior we're seeing with the Finnish API where, if the query is sufficiently large, it will keep returning pages of duplicate data indefinitely and never halt ingestion.
This has a few problems:
* Most days, the DAG returns 0 records but we still make 48 requests _per building_.
* Even on days with large amounts of data, the data is rarely distributed evenly across the day. In my tests I saw that the vast …
=> Finnish DAG: Dynamically generate timeslices depending on the amount of records

openverse_catalog/dags/common/slack.py, openverse_catalog/dags/maintenance/check_silenced_dags.py, tests/dags/common/test_slack.py, tests/dags/maintenance/test_check_silenced_dags.py
Fixes #953 by @AetherUnbound
This PR adds an _optional_ `task_id_pattern` field which can be used in the `SILENCED_SLACK_NOTIFICATIONS` Variable to specify a specific task within the DAG that a message should be silenced from.
This adds `task_id` as an _optional_ parameter to the various `slack.send_*` functions, so that the new behavior is backwards compatible. I tried to add it as a required variable initially but the changeset would have required so many modifications to various DAGs and tasks that it became unnecessarily cumbersome. Instead, this now adds the `task_id` to all exception calls (e.g. the `on_failure_callback` issuances of `send_alert`), which should cover the error cases we usually want to silence at least. We're fortunate that the silencing infrastructure is so …
=> Add task ID pattern to notification skip criteria

openverse_catalog/dags/providers/provider_api_scripts/freesound.py, tests/dags/providers/provider_api_scripts/test_freesound.py
Fixes #920 by @AetherUnbound 
Fixes #754 by @AetherUnbound 
* Updates Freesound to use the new `DelayedRequester::head` call
* Adds handling for an edge case when we get a 404 on a preview URL, which we use for getting filesize information. Since getting a 404 on the preview means the record is not playable on our frontend, we return `None` early and skip ingestion for these records.
Check out the new unit tests.
Run the Freesound DAG locally and verify that it still works.
One way to force a 404 for testing is to update the `_get_audio_file_size` method to append some nonsense to the end of the URL before making the request:
```
@retry(flaky_exceptions, tries=3, delay=1, backoff=2)
def _get_audio_file_size(self, url):
url = url + 'foo'
response = self.delayed_requester.head(url)
...
``` …
=> Discard audio file when preview 404s fetching filesize

pytest.ini, requirements_prod.txt
This PR upgrades Airflow to v2.5.1, which addresses an open security issue. I've also removed some warnings which we filter during testing since they are no longer raised!
1. `just build`
2. `just test --extended`
3. Launch the stack and make sure you can still run a DAG
errors.
<details>
```
Version 1.1
Suite D4700
Developer's …
```
=> Upgrade to Airflow 2.5.1, remove old warnings

DAGs.md, openverse_catalog/dags/providers/provider_api_scripts/europeana.py
Fixes #109 by @dravadhis 
This PR updates the Europeana DAG to use the new API endpoint under https://api.europeana.eu/ as noted in the [docs](https://pro.europeana.eu/page/search#get-started).
Happily I believe no additional changes were necessary. The API documentation is quite good and I was able to confirm all the fields we're using are present and unchanged, including the cursor based pagination. 
Tests should all continue to pass.
Try running the Europeana DAG locally and verify the script still works. For more thorough testing I did the following:
1. Set an `INGESTION_LIMIT` of 200
2. Run the DAG until it completes ingestion for a day with a good amount of data. `2022-11-04` had 200+ rows.
3. Find the tsv for your test day in the MinIO console and download it
4. Checkout `main` and …
=> Update Europeana endpoint

openverse_catalog/dags/common/storage/audio.py, openverse_catalog/dags/common/storage/image.py, openverse_catalog/dags/common/storage/media.py, openverse_catalog/dags/providers/factory_utils.py, openverse_catalog/dags/providers/provider_api_scripts/metropolitan_museum.py, openverse_catalog/dags/providers/provider_api_scripts/provider_data_ingester.py, openverse_catalog/dags/providers/provider_dag_factory.py, tests/dags/common/storage/test_media.py, tests/dags/providers/provider_api_scripts/test_provider_data_ingester.py, tests/dags/providers/test_factory_utils.py, tests/dags/providers/test_provider_dag_factory.py
Fixes #768 by @stacimc
This adds the `day_shift` as a suffix to the tsv filenames for reingestion workflows, in order to prevent a race condition where multiple reingestion days running at the same time will attempt to write to a file with the same name. @AetherUnbound did an excellent investigation and write-up of the bug in [this comment](https://github.com/WordPress/openverse-catalog/issues/768#issuecomment-1371463342).
This PR:
* adds the day_shift as a suffix, to ensure sufficient uniqueness. In non-reingestion DAGs, no additional suffix is added.
* removes the `generate_tsv_filenames` task while we're at it. This was a separate task that runs before the `pull_data` step and outputs the tsv filenames to XComs, so they can be grabbed later by the `copy_to_s3` task. For scripts using …
=> Add dayshift to tsv filenames for reingestion workflows

openverse_catalog/dags/common/storage/audio.py, openverse_catalog/dags/common/storage/columns.py, openverse_catalog/dags/common/storage/image.py, openverse_catalog/dags/common/storage/media.py, openverse_catalog/dags/providers/provider_api_scripts/wordpress.py, tests/dags/common/storage/test_audio.py, tests/dags/common/storage/test_columns.py, tests/dags/common/storage/test_image.py, tests/dags/common/storage/test_media.py, tests/dags/providers/provider_api_scripts/test_cleveland_museum.py
Fixes #557 by @krysal
This PR makes a number of non-trivial internal changes to the way URL validation is done, in order to accommodate WordPress Photo Directory needing the trailing slashes present to prevent 301 redirects. Part of this was made difficult by the fact that the URL validation step was occurring within the `URLColumn::prepare_string` method. Many of the same methods on similar `Column` derivatives are focused on ensuring the column value can be inserted appropriately into Postgres, so I think it makes sense to pull the URL validation higher into the stack and have it run when we're cleaning all of the other media metadata.
This also meant that some tests had to be adjusted based on now-incorrect assumptions about what testing values could be used for the URL fields.
I did a …
=> Preserve trailing slashes for WordPress URLs

openverse_catalog/dags/common/loader/sql.py, openverse_catalog/dags/providers/provider_dag_factory.py, tests/dags/common/loader/test_sql.py
Fixes #919 by @stacimc 
Some ingestion days for the `metropolitan_museum_reingestion_workflow` have been failing due to `DuplicateTable` errors. This is because the load table names are generated with the pattern: `provider_data_{media_type}_{provider_name}_{timestamp}_{day_shift}` -- but the very long provider name for this DAG causes the table name to be truncated in Postgres, such that the day_shift and part of the timestamp (which are required for uniqueness) are cut off.
This PR changes the order of the component parts of the table name such that `provider_name` is on the _end_, and is therefore the part that will get truncated if it is too long. This guarantees that `media_type`, `timestamp`, `day_shift`, and the first part of the provider name will fit.
Functionally, this means …
=> Ensure uniqueness of load table names

docker/airflow/Dockerfile, docker/local_postgres/Dockerfile
Fixes #1015 by @dhruvkb
This PR updates the `Dockerfile`s with small improvements.
errors.
<details>
```
Version 1.1
Suite D4700
have the right to submit it under the …
```
=> Update `Dockerfile`s with small improvements

DAGs.md, openverse_catalog/dags/providers/provider_api_scripts/wikimedia_commons.py, openverse_catalog/dags/providers/provider_dag_factory.py, openverse_catalog/dags/providers/provider_workflows.py, tests/dags/providers/provider_api_scripts/resources/wikimedia/continuation/wmc_continue_max_iter.json, tests/dags/providers/provider_api_scripts/test_wikimedia_commons.py
Fixes #725 by @stacimc
**Author's note**: This...is admittedly a really massive and complicated PR :sweat_smile: _(at least it seems that way to me!)_ Wikimedia's API is incredibly complicated, their documentation is hard to navigate, and there's a lot of "magic" that happens with it that can make it hard to introspect & grok. I've tried to summarize this all as best as I could in the DAG documentation, hopefully it's not too loquacious.
This PR changes the behavior of the Wikimedia ingestion to detect when a particular batch has been iterated over more than a certain number of times, and adjust the query parameters for the next request to try and reduce the amount of data returned. It does this by _excluding_ the fields which were returning massive amounts of data. As of today, none of …
=> Wikimedia: re-attempt large batches with reduced parameter selection

openverse_catalog/dags/providers/provider_api_scripts/inaturalist.py, tests/dags/providers/provider_api_scripts/test_inaturalist.py
Fixes https://github.com/WordPress/openverse-catalog/issues/1024 by @AetherUnbound (with some extremely timely and helpful mentorship from @AetherUnbound )
Adds some logging to the function that checks for new data on s3 at the beginning of the dag, and tests for the function that does the checking.
Do `just test`.
Beyond that, in the local environment, "s3" (actually minio) will always have timestamps from whenever you started the container and loaded in the test data for iNaturalist. So, you can test the "no past successful dag runs" case locally, and the "no new data" case locally. (Run the iNaturalist dag once locally and then run it again to confirm that it skips the rest of the dag and notes why in the logs.) 
In theory, you could go into minio and manually delete the test files and …
=> Add logging to iNaturalist date check

DAGs.md, openverse_catalog/dags/data_refresh/data_refresh_types.py
Sets the `schedule` for the image data refresh to `None`. This allows us to keep the DAG enabled in order to do manual runs, without the weekly scheduled runs triggering. We need to do this temporarily due to [ongoing issues](https://github.com/orgs/WordPress/projects/70/views/1?pane=issue&itemId=20824951) with the popularity matview refresh, which have caused the data refresh to dramatically increase in runtime and exceed the 1-week window.
This also increases the timeout for the matview refresh step from 3 days to 6 days, after the recent run timed out once again.
**Note**:  this PR does _not_ touch the audio data refresh. 
Pull this branch and run `just up`. Check that the `schedule` for the image data refresh is now `None` in the Airflow UI:
Enable the DAG and verify that no dag run …
=> Temporarily turn off scheduled image data refreshes, increase matview refresh timeout

openverse_catalog/dags/providers/provider_dag_factory.py, openverse_catalog/dags/providers/provider_reingestion_workflows.py, openverse_catalog/dags/providers/provider_workflows.py, tests/dags/providers/test_provider_dag_factory.py, tests/dags/providers/test_provider_workflows.py
Fixes #724 by @AetherUnbound 
Adds an Airflow Variable that can be used optionally to temporarily alter the execution timeouts for *any task in a provider DAG*, using a `task_id_pattern`. The timeout overrides are configured in the format `<days>d:<hours>h:<minutes>m:<seconds>s`. Example using the `CONFIGURATION_OVERRIDES` Airflow variable:
```
{
"brooklyn_museum_workflow": [
{
"task_id_pattern": "pull_image_data",
"timeout": "10h"  # 10 hrs
},
{
"task_id_pattern": "report_load_completion",
"timeout": "4s"  # 4 seconds
}
],
"metropolitan_museum_reingestion_workflow": [
{
"task_id_pattern": "upsert_data",
"timeout": "6d:11h"  # 6 days, 11 hours
}
],
"inaturalist_workflow": [
{
"task_id_pattern": "load_taxa",
"timeout": "6d:10h:9s"  # 6 days, 10 hours, 9 seconds
},
{
"task_id_pattern": …
```
=> Add Airflow variable used to configure overrides for task timeouts

DAGs.md, openverse_catalog/dags/common/loader/provider_details.py, openverse_catalog/dags/maintenance/flickr_audit_sub_provider_workflow.py, tests/dags/maintenance/test_flickr_audit_sub_provider.py
Fixes #676 by @zackkrida 
We want to identify some additional curated sub-providers for Flickr.
Ideally, I'd love to be able to identify large [providers of cc-images](https://www.flickr.com/creativecommons/) and hand select some high quality sources. I was not able to find good sources of this information, or an efficient way of querying the API for this.
As a quick initial plan, I took a look at the member institutions of the [Flickr Commons](https://www.flickr.com/commons/). The list of institutions is accessible via the API. Unfortunately, many of these provide a general "no known copyright restrictions" disclaimer, rather than a CC license.
This PR adds a simple DAG that looks for member institutions of the Flickr Commons which (1) are not already configured as sub-providers and (2) …
=> Add flickr sub provider auditing dag

openverse_catalog/dags/providers/provider_api_scripts/jamendo.py, tests/dags/providers/provider_api_scripts/test_jamendo.py
Fixes https://github.com/WordPress/openverse/issues/871 (from an upstream data perspective)
This PR adds a trailing slash to Jamendo thumbnail URLs if it does not already have one. This is to ensure compatibility with our thumbnail provider, Photon, which is not able to follow redirects when generating thumbnails. See the above issue for more details.
`just test` should be sufficient, since this alters the output of one of the tests.
errors.
<details>
```
Version 1.1 …
```
=> Add trailing slash to Jamendo thumbnail URLs

openverse_catalog/dags/common/licenses/licenses.py, tests/dags/common/licenses/test_licenses.py, tests/dags/providers/provider_api_scripts/test_jamendo.py
Fixes #1027 
This PR adds a set of valid license URLs to check the URLs before sending a network request to validate it.
It also lower-cases the URL (for `CC0` urls, for example) and adds a trailing slash.
This PR caught an error in the licenses in the Jamendo tests. In the expected license URL, we did not have a trailing slash. 
```
url="https://creativecommons.org/licenses/by-nc/2.0",
raw_url="http://creativecommons.org/licenses/by-nc/2.0/",
```
The tests should pass?
=> Improve license URL validation

DAGs.md, openverse_catalog/dags/maintenance/add_license_url.py
Related to #511 by @obulat
This PR adds `license_url` to the `meta_data` jsonb field where the `meta_data` field is `NULL`. 
To make the query faster, we split it into several steps:
1. Count the number of rows where `meta_data` is `NULL`.
2. Update the `meta_data`:
a. Select all `identifier`s of the items where `meta_data` is `NULL`. Having `identifier`s will enable us not to do `sequential scan` through all of the database (i.e., not to test each row individually), and only work with the 366 974items identified in the related issue.
b. For each `license` and `license_version` pair, we run the `UPDATE` query setting the `meta_data` to `{"license_url": <URL>}`. Note: I'm using `Json` here although the column is `jsonb`. I'm not sure if it's correct, but it works locally.
3. The final …
=> Add a DAG for backfilling license_url when meta_data is null

LICENSE
This PR updates the `LICENSE` file to match the owner in the main repo. This is an attempt to reduce merge conflicts when this repo is eventually merged into `WordPress/openverse`.
Marking the priority as high as these PRs are pre-cursors to the monorepo merge.
=> Update `LICENSE` to match main repo

openverse_catalog/dags/maintenance/add_license_url.py
Fixes #1044 
This PR updates the second step in the DAG to replace many `SELECT` queries with `SELECT`ing all items with `NULL` in meta_data, then grouping of the items to update using Python function, and then running one `UPDATE` query per license pair (if necessary). Hopefully, this should be much faster than the previous run.
This PR also sets the trigger rule for the last step, because otherwise it was skipped if the second step was skipped.
Same as #1005.
=> Use Python to group items by license to speed up the query

DAGs.md, openverse_catalog/dags/maintenance/check_silenced_dags.py, openverse_catalog/dags/providers/provider_api_scripts/provider_data_ingester.py, tests/dags/maintenance/test_check_silenced_dags.py, tests/dags/providers/provider_api_scripts/test_provider_data_ingester.py
Fixes #702 by @stacimc 
Adds a `SKIPPED_INGESTION_ERRORS` Airflow variable that can be used to configure a provider DAG to skip specific ingestion errors, continuing ingestion and reporting them in aggregate at the end. Errors whose message _or class_ match the configured predicate will be skipped.
Much like `SILENCED_SLACK_NOTIFICATIONS`, the predicate must be associated to an open GitHub issue:
```
{
"wikimedia_reingestion_workflow": [
{
"issue": "https://github.com/WordPress/openverse-catalog/issues/367", 
"predicate": "Foo"
}
],
"wikimedia_commons_workflow": [
{
"issue": "https://github.com/WordPress/openverse-catalog/issues/725", 
"predicate": "ValueError"
}
]
}
```
The `check_silenced_dags` DAG has also been updated to check this variable for closed GitHub issues, and report them: …
=> Add option to skip specific ingestion errors

README.md
Update documentation with fix for the following issue: https://github.com/WordPress/openverse-catalog/issues/394 
Added a reference to the old repository for the catalog (https://github.com/cc-archive/cccatalog) into the new repository's documentation.
=> Update README.md with documentation reference

openverse_catalog/dags/providers/provider_api_scripts/smk.py
Fixes #1020 by @AetherUnbound
Fast-follow to #1003, this PR reverts the watermark change made to the SMK ingestion DAG in order to preserve the primary images. See that PR and #875 for context.
Tests should pass, running this DAG locally should generate data which has `watermarked=false` in the database.
errors.
<details>
```
Version 1.1
Suite D4700
license document, but …
```
=> Remove watermarked setting for SMK

openverse_catalog/dags/maintenance/add_license_url.py
After the last run of the `add_license_url` DAG, we still have more than 8000 records with `NULL` in `meta_data`. Most of them are due to the license name being upper case (CC0 instead of cc0).
This PR converts the license name to lower case before using it to create the URL. It also updates both the `meta_data` and the `license`.
To make this DAG faster, I've removed the first step, which basically just repeats the first part of the second task selecting the items where meta_data is NULL.
This DAG also saves the data (identifier, license, license_version) for invalid license pairs that cannot be fixed to S3 for further investigation.
=> Handle the upper case licenses in the add_license_dag

openverse_catalog/dags/providers/provider_api_scripts/flickr.py, openverse_catalog/dags/providers/provider_api_scripts/provider_data_ingester.py, openverse_catalog/dags/providers/provider_api_scripts/time_delineated_provider_data_ingester.py, tests/dags/providers/provider_api_scripts/test_flickr.py, tests/dags/providers/provider_api_scripts/test_time_delineated_provider_data_ingester.py
Fast follow for Flickr backfill.
Related to #1007.
This PR attempts to handle situations where the Flickr API returns excessively large batches of data. The logic should be documented pretty thoroughly in the code, but here's a refresher:
The Flickr API will only return 4,000 unique records for any given set of query params; after that, it will just infinitely return duplicates. Consequently, we have to try to query the API in such a way that we get batches with less than 4,000 records each. Up until now, we have been doing this using the `TimeDelineatedProviderDataIngester` to break the day into small time intervals for ingestion.
There is a limit to the granularity of data by time interval, though -- once you reduce the interval size to about 5 minutes, the number of records stays the …
=> Update Flickr large batch handling

openverse_catalog/dags/providers/provider_api_scripts/provider_data_ingester.py
The `ProviderDataIngester` includes error handling that, among other things, logs the last `query_params` reached by the DAG before an error is encountered during ingestion, which is helpful for debugging or resuming a failed DAG. `AirflowException`s are exempted from this custom handling, but that means we also don't get the `query_param` logging when a task is stopped by Airflow.
This PR changes nothing about the handling of those exceptions, but just adds a log for the last query params hit before raising. **This is useful when a `pull_data` task times out, because we can see exactly where the DAG managed to get to and resume it at that point.**
Update the `pull_timeout` for a provider ingester to something small. You can do this in the `provider_workflows.py` file or via the Airflow …
=> Log last query_params hit before AirflowTaskTimeout

DAGs.md, openverse_catalog/dags/providers/provider_workflows.py
Fixes #1025 by @AetherUnbound
This PR changes the schedule interval of the iNaturalist DAG so that it runs on the _second_ day of the month (rather than on the first day of the month with all the other `@monthly` runs.
1. `just up`
2. Check the list of DAGs at http://localhost:9090 and see that the schedule interval for iNaturalist reflects the change here
errors.
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute …
```
=> Offset iNaturalist DAG from monthly by one day

DAGs.md, openverse_catalog/dags/maintenance/fix_phylopic_foreign_identifier.py
Fixes #1073 by @krysal 
Related to #1060
This PR adds a one-time-run DAG to update this field for Phylopic images, which extract the uuid from the old URL and updates the `foreign_identifier` with that value, so the v2 of the provider DAG can update the rows instead of creating new ones.
This can actually be tested with production data following the steps @AetherUnbound used in https://github.com/WordPress/openverse-catalog/pull/1060#pullrequestreview-1359810476.
1. Upload production PhyloPic data. If you have permission, you can follow the steps cited in the previous (review) link or download the data [here](https://gist.github.com/krysal/0721e8109338957d5fce0ea1904c5818/raw/bfe88278ba7d0804f9ff1b1533c3639bd8f01975/phylopic_v1_prod.csv).
2. Checkout this branch and run the …
=> Create DAG to fix PhyloPic's `foreign_identifier` column

openverse_catalog/dags/common/storage/media.py, openverse_catalog/dags/providers/provider_api_scripts/metropolitan_museum.py, tests/dags/common/storage/test_media.py, tests/dags/providers/provider_api_scripts/test_metropolitan_museum.py
Fixes #1019 by @stacimc 
This PR:
* raises a `ValueError` in the MediaStore's `clean_media_metadata` if any of the required fields `foreign_landing_url`, `url`, and `foreign_identifier` are missing.
* Adds some new error handling for Metropolitan:
* Returns early if no image urls (primary or additional) can be pulled
* Handles missing `isPublicDomain` key (in addition to explicit `False`)
* Returns early if missing foreign landing url
View the new tests.
The Metropolitan issue is hard to reproduce organically. You can manually update the metropolitan DAG code to add a `None` image [here](https://github.com/WordPress/openverse-catalog/blob/main/openverse_catalog/dags/providers/provider_api_scripts/metropolitan_museum.py#L93):
```
image_list = [main_image] + other_images + [None]
```
Then …
=> Check required fields in media store

openverse_catalog/dags/providers/provider_api_scripts/metropolitan_museum.py, tests/dags/providers/provider_api_scripts/test_metropolitan_museum.py
Fixes #1019 by @stacimc 
Previously we added handling to the Metropolitan DAG for when we receive urls that are `None`. It turns out we also sometimes receive empty strings.
This PR discards records with empty string urls within Metropolitan. We should consider also handling this in the media store; currently the `validate_url_string` method used by the media store returns `None` when it cannot validate a url. We _could_ instead raise an error here. I did not do so in this PR because I did not want to make changes that apply across all DAGs before the catalog code freeze, and the fix will still need to be made in Metropolitan regardless. If folks think this change would be a good idea, I can create an issue for it.
This ordinarily takes a very long time to reproduce, but good news, I …
=> Handle empty string urls for Metropolitan

openverse_catalog/dags/maintenance/rotate_db_snapshots.py, tests/dags/maintenance/test_rotate_db_snapshots.py
Fixes issue found while testing the DAG:
```
[2023-04-11, 01:29:12 UTC] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/operators/rds.py", line 103, in execute
create_instance_snap = self.hook.conn.create_db_snapshot(
File "/usr/local/lib/python3.10/functools.py", line 981, in __get__
val = self.func(instance)
File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 630, in conn
return self.get_client_type(region_name=self.region_name)
File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 595, in get_client_type
return session.client(
File …
```
=> Add region to rotate_rds_snapshots DAG
